frappe/lms

community/hooks.py, community/lms/widgets/HelloWorld.html, community/test_widgets.py, community/widgets.py
Widgets are reusable jinja templates which can be used in other
themplates. Widgets are written in widgets/ directory in every frappe
module and can be accessed as `{{ widgets.WidgetName(...) }}` from any
template.
=> feat: widgets interface

community/www/courses/index.py
1. Slug field was being referenced on the courses page.
2. As we don't have a slug field anymore, the courses page was not appearing on new sites.
=> fix: removed slug field ref from courses page

community/lms/doctype/lms_batch_membership/lms_batch_membership.js
1. LMS Batch Membership has a field member which is linked to the User doctype.
2. This link field was not considering Website Users.
3. Added a filter ignore_user_type to allow Website Users.
=> fix: ignore user permission for membership

community/lms/doctype/chapter/chapter.py, community/lms/doctype/exercise/exercise.json, community/lms/doctype/exercise/exercise.py, community/lms/doctype/lesson/lesson.json, community/lms/doctype/lesson/lesson.py, community/lms/doctype/lms_course/lms_course.json, community/lms/doctype/lms_course/lms_course.py, community/lms/widgets/Exercise.html, community/www/batch/progress.html, community/www/batch/progress.py
Some lessons gets deleted and some new ones get added as part of course creation and it may happen then some of the lesson index may become inconsistent.  Also, we would like to maintain an index for the  exercises. To support both of these, added actions to reindex lessons  and exercises to the course doctype.
Changes:
- add `index_label` field to lesson and exercise and that would have values like `"1.2"`, `"2.3"`  etc.
- add `index_` field to the exercise (that is already present in lesson)
- add actions to "Reindex Lessons"  and "Reindex Exercises" to desk to update index and index_label fields
- remove index and index_label from exercises that were not part of any lesson
- show exercise like "Exercise 1.2: Draw a circle", using the index_label 
- ignore orphan exercises when showing …
=> feat: actions to reindex lessons and exercises

community/lms/doctype/lesson/lesson.py
The exercises being listed in unpredicted order instead of the order
they were listed in the lesson. The was because the `index_` of the
exercise was never updated. Fixed this by updating the `index_` whenever
a lesson edited. However, the user still need to run reindex exercises
on the course correct the ordering, which wasn't possible earlier.
=> fix: issue with numbering the exercises

community/community/profile_tab.py, community/www/profiles/profile.html, community/www/profiles/profile.py
Added ProfileTab class to represent a profile tab and made the profile
page render the tabs specified in the hook `profile_tabs`. This allows
plugging in new tabs in the profile page without makeing any changes to
the community module.
=> feat: pluggable profile tabs

community/www/batch/learn.py
Added `is_member` field to page_context of learn page. This is required to disable exercises to non-members.
=> feat: include membership info in page context

community/community/widgets/Avatar.html, community/hooks.py, community/lms/web_form/profile/profile.js, community/lms/widgets/CourseTeaser.html, community/lms/widgets/InstructorSection.html, community/lms/widgets/MemberCard.html, community/lms/widgets/Reviews.html, community/page_renderers.py, community/templates/discussions/reply_card.html
- Added `profile_url_prefix` to hooks. The default is `/users/` and can be set to`/` to make it top-level
- Added function `get_profile_url(username)` available to all templates and updated all links to profiles using that
- Added /profile_/foo URL to redirect to the profile page to make it possible to redirect to profile page from JS
Closes #192
=> Added support for making profile urls to be top-level

community/templates/discussions/reply_card.html
=> fix: discussions markdown support

community/lms/doctype/chapter/chapter.json, community/lms/doctype/chapter_reference/chapter_reference.json, community/lms/doctype/chapter_reference/chapter_reference.py, community/lms/doctype/lesson/lesson.json, community/lms/doctype/lesson_reference/lesson_reference.json, community/lms/doctype/lesson_reference/lesson_reference.py, community/lms/doctype/lms_course/lms_course.json, community/lms/doctype/lms_course/lms_course.py, community/lms/doctype/lms_quiz/lms_quiz.json, community/lms/widgets/ChapterTeaser.html, community/public/css/style.css, community/public/node_modules, community/www/batch/learn.html, community/www/courses/index.py
1. Sorting on all courses page. Upcoming courses will appear after live courses.
2. Message for course instructors if lesson is not available for preview.
3. Enabled renaming on Chapter, Lesson and Quiz
4. Changed the name of Chapters doctype to Chapter Reference.
5. Changed the name of Lessons doctype to Lesson` Reference
=> fix: minor issues

community/lms/widgets/ChapterTeaser.html, community/www/batch/learn.html
1. The preview message for instructors was appearing even for lessons that are available for preview. Fixed that.
2. Changed the tooltip message for the course outline to match with the message that appears above the lesson.
=> fix: preview message

community/lms/doctype/lms_course_interest/lms_course_interest.py
It is possible to create duplicate entries of course interest if the course page is opened it in two tabs and the user clicks "notify when available" button on each of this. 
This PR takes care of the issue by checking if an entry already exists before creating a new one.
=> fix: avoid creating duplicate entries of LMS Course Interest

community/www/courses/index.html, community/www/courses/index.py
1. Separating Live and Upcoming Courses on the All Courses Page.
=> feat: live and upcoming course headers

community/patches.txt, community/patches/v0_0/rename_chapter_and_lesson_doctype.py
1. Reload all affected doctypes in patch that handles renaming of Chapter and Lesson doctype
=> fix: relaod doctypes in patch

community/www/batch/learn.js
**Issue:**
1. API call to save lesson progress was pointing to old doctype location.
**Fix:**
1. Changed the API call to point to the new doctype location
=> fix: api call for progress save

community/lms/doctype/lms_quiz_result/lms_quiz_result.json
**Issue:**
The Quiz submission doctype was throwing an error when the length of questions exceeded 140 characters.
**Fix:**
Question field in LMS Quiz Result table was a Data field. Changed this field to Text field.
=> fix: quiz question length issue

community/lms/doctype/course_lesson/course_lesson.py, community/lms/doctype/lms_batch_membership/lms_batch_membership.json, community/lms/doctype/lms_course/lms_course.py, community/lms/report/course_progress_summary/course_progress_summary.py, community/lms/widgets/CourseCard.html, community/overrides/user.py, community/patches.txt, community/patches/v0_0/add_progress_to_membership.py, community/www/batch/learn.html, community/www/courses/course.html
**Issue:**
1. Course Progress Summary report now has a huge amount of data. This results in a timeout before the report completes execution.
2. Converting it to a prepared report does not help because prepared reports can't have charts
**Fix:**
1. Added a progress field in membership doctype.
2. Added a patch to add progress in this field.
3. Now when a lesson would be marked as complete, updated progress will be calculated and saved in the field in membership doctype
4. All files that display progress will fetch data from this field.
5. Course progress summary report will also fetch progress from this field.
=> fix: get progress from membership

school/lms/report/course_progress_summary/course_progress_summary.js, school/lms/widgets/CourseCard.html, school/public/css/style.css
1. Improved alignment for course cards.
2. Reduced space between CTA label and arrow.
3. Removed padding around breadcrumb.
4. Made card divider thinner.
=> style: course cards, card dividers, breadcrumbs

school/lms/web_template/courses_enrolled/courses_enrolled.html, school/lms/widgets/Reviews.html, school/www/batch/learn.html
Improve empty states for:
**Reviews:**
**Discussions:**
**Course Enrolment Template:**
1. Reduced font size for the byline.
**Depends on** https://github.com/frappe/frappe/pull/14916
=> style: better empty states

school/public/css/style.css, school/templates/search_course/search_course.html, school/templates/search_course/search_course.js
**Issue:**
1. The search empty state was getting removed from dom on closing.
2. So when the empty state was closed and later an empty state occurred, the banner was not appearing.
**Fix:**
1. Replaced bootstrap closing with custom.
=> fix: search empty state improvements

school/public/css/style.css, school/www/courses/course.html, school/www/courses/course.js
**Issue:**
Previously when a user used to opt to be notified for the course, the button used to become disabled. There was a tooltip with a message that informed the user about the same.
This was not a good UX for the mobile as no tooltip was visible there. A disabled button is not a clear indicator.
**Fix:**
After clicking on notify me the button would no more be visible. A message will be shown to the users informing them of the same.
https://user-images.githubusercontent.com/31363128/143407377-b8ae55d8-a583-4ebd-b0b5-017b15907f5b.mov
=> fix: notify me ux

school/public/css/style.css, school/www/batch/learn.html, school/www/batch/learn.js
**Issue:**
Previously, marking a lesson as complete was a manual process. Users had to click a separate button to mark the lesson as complete. Most users did not do it resulting in the loss of important information.
**Fix:**
We have made marking the lesson as complete a bit less manual. Instead of a button, it will now be a checkbox that will be checked by default. When users move to the next lesson, the current lesson will be marked as complete.
To not mark a lesson as complete, they can uncheck the checkbox.
=> fix: mark as complete behaviour

school/lms/doctype/lms_settings/lms_settings.json, school/www/profiles/profile.html, school/www/profiles/profile.py
Platform maintainers can now configure if the user's primary contact information like their Email address and Mobile Number should be visible on their profile page.
They have to enable **Hide Primary Contact from Profile Page** from **LMS Settings** for the same.
=> feat: hide primary contact from profile

school/lms/doctype/lms_course/lms_course.py, school/lms/doctype/lms_course_review/lms_course_review.py, school/www/courses/course.js
**Issue:**
1. Frappe now has [Fractional Ratings](https://github.com/frappe/frappe/pull/15426).
2. Because of this on the course page the ratings were not reflected properly.
**Fix:**
1. Adjusted out rating display to consider the rating field options if present else considers it as 5 and compute the ratings.
=> fix: rating field issue

school/overrides/user.py, school/www/profiles/profile.html, school/www/profiles/profile.py
1. Not showing empty Contacts section if there is no information in it.
2. Increasing icons size on the overview section.
3. Improved condition for profile completion
=> fix: profile page sections

school/overrides/user.py
**Before:**
Community Page was showing disabled users.
**After:**
=> fix: Exclude disabled users from Community Page

school/job/doctype/job_opportunity/job_opportunity.json, school/job/doctype/job_opportunity/job_opportunity.py, school/job/doctype/job_settings/job_settings.js, school/job/doctype/job_settings/job_settings.json, school/job/doctype/job_settings/job_settings.py, school/job/doctype/job_settings/test_job_settings.py, school/public/css/style.css, school/templates/emails/job_report.html, school/templates/job_card.html, school/www/community/index.html, school/www/courses/index.html, school/www/jobs/index.html, school/www/jobs/index.py, school/www/jobs/job.html, school/www/jobs/job.js
1. Admins can now select if users should post jobs from the website.
2. Job Opportunities can now be disabled.
3. No approval would be needed for Job opportunities from now. Instead, if users find a particular posting as suspicious, they can report such posts.
https://user-images.githubusercontent.com/31363128/148960266-185ce3b8-9d8c-412a-b7ba-31c1eaea5043.mov
=> fix: jobs ui and reporting

school/plugins.py, school/www/batch/learn.py
Pass the context to page extensions to allow them to make decisions
based on the context. For example, an extension to load the course
specific scripts. This is currently not possible because the course
details are not availale to the page extensions. Made this possible by
passing the context to page extensions.
=> feat: pass context to page extensions

school/hooks.py, school/lms/utils.py, school/lms/widgets/CourseOutline.html, school/plugins.py, school/public/css/style.css, school/templates/quiz.html, school/www/batch/learn.html, school/www/courses/course.js, school/www/utils.py
**Course Page Redesign:**
---
---
=> feat: course page redesign

lms/lms/doctype/course_evaluator/course_evaluator.py, lms/lms/doctype/lms_course/lms_course.json, lms/public/css/style.css, lms/www/batch/learn.html, lms/www/batch/learn.js, lms/www/courses/course.html, lms/www/courses/course.js, lms/www/courses/course.py, lms/www/courses/index.py
1. Previously, the flow allowed two or more people to book the same slot for evaluation. Now, if a person has already booked a slot, it wouldn't be visible to others.
2. Also, when a user used to select a slot, it would be submitted directly. Now there is an explicit submit button ensuring that users confirm the slot before they submit.
=> fix: certificate request flow and other minor changes

lms/lms/doctype/exercise/test_exercise.py, lms/lms/doctype/lms_batch_membership/test_lms_batch_membership.py, lms/lms/doctype/lms_certificate/test_lms_certificate.py, lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.js, lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.json, lms/lms/doctype/lms_certificate_request/lms_certificate_request.js, lms/lms/doctype/lms_course/lms_course.json, lms/lms/doctype/lms_course/test_lms_course.py, lms/lms/test_utils.py, lms/lms/utils.py, lms/overrides/test_user.py, lms/www/courses/course.html, lms/www/courses/course.py
1. Certificate Evaluations can now have a maximum number of attempts. This can be configured through the LMS Course doctype.
2. Once a user exceeds a maximum number of attempts in the specified duration, they can't apply within that duration anymore.
3. A status field has been added to LMS Certificate Evaluation to determine if a user should re-apply.
=> feat: max attempts for certificate evaluation

lms/hooks.py, lms/overrides/user.py
1. Renamed app from LMS to Frappe LMS in hooks.py
2. Rectified username validation conditions to detect and remove Hyphen(-).
=> fix: renamed apps in hooks and rectified username validation conditions

lms/patches.txt, lms/patches/v0_0/delete_old_module_docs.py
Deleted doctypes, webforms and module def for old unused modules Hackathon, Conference, Event Management
=> fix: delete doctypes from old modules

lms/lms/doctype/course_lesson/course_lesson.json, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/doctype/lms_course/lms_course.py, lms/lms/utils.py, lms/overrides/user.py, lms/public/css/style.css, lms/www/batch/learn.html, lms/www/batch/learn.js
1. Previously YouTube Videos and Quizzes were added to lessons using special markdown syntax. Eg {{ YouTubeVideo("Video ID") }}
2. This syntax was not very obvious to use for the first time. Users needed an explanation and referred to the documentation and help articles below the lesson page for the same.
3. To make this easy to add, fields have been added for Youtube and Quiz.
4. For YouTube, users will add the shareable URL of the video.
5. For quizzes they will add the quiz id.
6. YouTube Video will appear at the top of the lesson and the quiz will appear at the bottom.
=> feat: separate inputs for adding youtube video and quiz

lms/lms/widgets/CourseCard.html, lms/lms/widgets/Reviews.html, lms/public/css/style.css, lms/www/batch/learn.html, lms/www/profiles/profile.html
1. If there are one or two instructors for a course, their names will be directly shown in relevant places. If there are more than 2 instructors, then we will show the name of the first instructor followed by the remaining instructor count as others.
2. Write a review button will now be secondary
3. After recent web form changes, for editing a profile from the profile page, it used to take users to the read-only version of the web form first, where they had to click on Edit Response to edit. Now they will be redirected taken to the editable form.
4. Fixed #361
=> fix: ui misc

lms/www/batch/learn.js, lms/www/courses/course.html, lms/www/courses/course.js
1. Description Field is now a text editor. It accepts normal as well as markdown content
=> fix: text editor for description field

lms/job/doctype/job_opportunity/job_opportunity.py, lms/lms/doctype/lms_course/lms_course.py, lms/lms/utils.py, lms/overrides/user.py, lms/www/profiles/profile.html
1. While uploading attachments, Frappe Framework has made the default to private.
2. Since it's a small checkbox, it goes unnoticed by a lot of users. So when they add a profile image, course image, or company logo, it gets saved as private, and it's not visible to other users.
3. So, now whenever a user saves these images, there will be a check from the backend if these are private and if yes then they will be made public automatically.
=> fix: change private files to public for company logo, user and course image

lms/public/css/style.css, lms/www/batch/learn.html, lms/www/batch/learn.js
1. Previously, the progress tracking was based on users' input. When the user used to move to the next lesson their progress was marked. They also had an option to mark a completed lesson as incomplete again.
2. If users used to visit a lesson from the sidebar the progress of the previous lesson was not marked because the next button was not clicked.
3. To make the process simpler, a lesson will now be marked complete when users scroll through the lesson.
=> fix: progress tracking

lms/hooks.py, lms/lms/utils.py, lms/lms/web_template/dashboard_stats/dashboard_stats.html, lms/lms/web_template/dashboard_stats/dashboard_stats.json, lms/public/css/style.css, lms/templates/dashboard_stats.html, lms/www/dashboard/index.html
A web template that will show some important LMS stats.
This is configurable through the page building block settings.
=> feat: dashboard stat

lms/hooks.py, lms/install.py
When the app was uninstalled, the custom fields created for User doctype still used to be present. They caused issues in opening and editing the user doctype. So now when the app is uninstalled, the custom fields will be deleted.
Related to: #393 and #369
=> fix: delete custom fields after app in uninstalled

lms/lms/web_template/lms_statistics/lms_statistics.html, lms/lms/web_template/lms_statistics/lms_statistics.json, lms/templates/statistics.html
1. Added title and subtitle to the LMS Statistics template
2. Removed the k format for numbers.
=> fix: stats template

lms/hooks.py, lms/lms/utils.py, lms/www/batch/learn.py, lms/www/courses/course.py, lms/www/courses/index.py
Previously, when a Guest users used to visit the new course creation page from the portal, they were redirected to the course list page, because they should not be allowed to create a new course. There was no proper message given to the user here and the users got confused.
A message will be shown to users in this scenario where they will be asked to log in.
=> fix: course permission messages

lms/www/courses/index.html, lms/www/courses/index.js, lms/www/profiles/profile.js
There are tabs on the course list and profile page. Previously, when the tabs were changed on this page, there was no hash change in the URL. People were unable to share a particular tab because of this.
The hash in the URL will now change with the tab change.
=> fix: tab urls

lms/templates/statistics.html
Stat numbers will be formatted with commas.
=> fix: format stats

lms/www/classes/class.html, lms/www/classes/progress.html, lms/www/classes/progress.py
Display the last active time of the student on the class and progress page.
=> feat: last active time of class students

lms/hooks.py, lms/install.py, lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.py, lms/lms/doctype/lms_class/lms_class.json, lms/lms/web_form/evaluation/evaluation.json, lms/lms/web_form/evaluation/evaluation.py, lms/patches.txt, lms/www/assignments/assignment.html, lms/www/assignments/assignment.py, lms/www/classes/class.html, lms/www/classes/class.py, lms/www/classes/index.html, lms/www/classes/index.py, lms/www/classes/progress.html, lms/www/classes/progress.py
1. Students will now be able to see the Class dashboard.
2. They however won't be able to perform any operations. Those rights are only reserved for the Moderator.
3. Pages like the assignment and evaluation details will only be visible to the Moderator and the student whose document it is.
4. The students when they open their respective assignments from the class tab will not be able to make any modifications. They can just see the details. 
1. Classes have been added as a nav item through a patch and on installation.
1. If the Moderator wishes to display some more information to their class they can do so with the custom code field. The HTML entered in this field will be visible on the class details page.
=> feat: students view for classes

lms/lms/widgets/CourseCard.html
1. Don't fetch membership information for guest users.
2. Fetch only current course membership for each card.
=> perf: course card improvements

lms/install.py, lms/lms/doctype/lms_settings/lms_settings.json, lms/lms/utils.py, lms/patches.txt, lms/patches/v0_0/rename_instructor_role.py
Rename Instructor role to Course Creator because there is already a role with the same name in Education App
=> fix: rename instructor role to course creator

lms/lms/utils.py, lms/lms/widgets/CourseCard.html
When there is no lesson in a course, and the user clicks on the Start Learning button, they are redirected to lesson 1.1. But as no such lesson exists, it leads to a 404 page.
The Start Learning button will not be shown when there are no lessons in a course.
=> fix: hide start learning when no lesson in course

lms/overrides/user.py
After creating a new site, an Administrator was redirected to the /courses page even before completing the setup wizard.
Before redirecting to the /courses page, it will be checked if the setup wizard is complete. Users will be only redirected after the completion of setup wizard.
=> fix: login redirect condition

lms/hooks.py, lms/overrides/user.py, lms/patches.txt, lms/patches/v0_0/user_singles_issue.py
Blogs were not getting rendered. On visiting the page this error used to appear.
This was happening because using the hook on_login, the user's country was being set using their IP. And if the user was not passed correctly, then it was creating an entry for User doctype in tabSingles. For details refer  to https://github.com/frappe/frappe/issues/19471
The avatar for blogs queries the get_user_info_for_avatar function with user_id as None. This resulted in a faulty response from the tabSingles which caused the issue.
No need to set country from IP during login. The call has been removed. A patch will delete the User doctype entries from tabSingles.
=> fix: user doctype singles issue

lms/lms/doctype/lms_settings/lms_settings.json, lms/overrides/user.py
#472 
The course list page used to be the default home once the setup wizard was complete and any user logged into the system. This was a problem with users who had other apps also installed on the site.
As a fix, there will now be a setting for this in LMS Settings. A checkbox to **Make LMS the default home**. Only when this is checked, the course list will be default home. Else everything will work as it should.
=> fix: default home setting

lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.js, lms/lms/doctype/lms_certificate_request/lms_certificate_request.js, lms/lms/doctype/lms_certificate_request/lms_certificate_request.json, lms/lms/doctype/lms_certificate_request/lms_certificate_request.py, lms/lms/doctype/lms_course/lms_course.json, lms/lms/doctype/lms_settings/lms_settings.json, lms/lms/doctype/lms_settings/lms_settings.py
1. A new configuration is added to LMS Setting, **Send calendar invite for evaluation**.
2. When a new Certificate Request is created, it will send a calendar invite to the evaluator and the participant if the above configuration is checked.
3. It will create an event in the Event doctype which will in turn send the calendar invite.
4. For this to work, it is necessary for **Google Settings** to be enabled and for each instructor to have a **Google Calendar** set in the system.
=> feat: event for evaluation

lms/lms/doctype/lms_course/lms_course.py, lms/patches.txt, lms/patches/v0_0/video_embed_link.py, lms/www/courses/course.html
1. To add a preview video, previously users had to add the complete iframe src that youtube provides.
2. This involved multiple clicks on the youtube platform plus was confusing for users.
3. This PR simplifies the process. Now users just need to end the last parameter of the URL that youtube provides for sharing a video. The rest will be handled by the app.
=> fix: accept only embed id for preview video

lms/lms/doctype/lms_certificate_request/lms_certificate_request.json, lms/lms/notification/certificate_request_creation/certificate_request_creation.json
The notification sent when a Certificate Request is created will now be sent to both the Member and the Evaluator.
=> fix: certificate request notification

lms/public/js/setup_wizard.js
When the app was installed on a new site, after completion of the setup wizard, the user was redirected to the Courses Dashboard. This should not happen as the user has not yet opted to have LMS as the default home.
After completion of the setup wizard, the user will now be redirected to the backend desk.
=> fix: redirection after completing setup wizard

lms/lms/doctype/lms_quiz/lms_quiz.py, lms/lms/doctype/lms_quiz/test_lms_quiz.py, lms/lms/doctype/lms_quiz_question/lms_quiz_question.json, lms/patches.txt, lms/patches/v0_0/add_question_type.py, lms/public/css/style.css, lms/templates/quiz.html, lms/www/batch/learn.js, lms/www/batch/quiz.html, lms/www/batch/quiz.js, lms/www/batch/quiz.py
You can now have quiz questions with User Input. In the quiz creation form, the instructor must select a question type. If the type is Choices, the question will be in the form of multiple options as it was before. If they choose the type User Input, they will have to provide a Possible Answer. Min 1 and Max 4 possible answers can be provided.
Users will have to enter an answer for this type of question, when they click the check button the answer will be matched with all possible answers. If a match is found, the answer will be considered as correct. If not it will be considered incorrect. The matching will be case-insensitive.
=> feat: quiz with user input

lms/lms/doctype/course_lesson/course_lesson.json, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/doctype/lms_course/lms_course.json, lms/lms/utils.py, lms/lms/widgets/CourseOutline.html, lms/patches.txt, lms/patches/v0_0/convert_course_description_to_html.py, lms/patches/v0_0/convert_lesson_markdown_to_html.py, lms/public/css/style.css, lms/www/batch/learn.html, lms/www/batch/learn.js, lms/www/courses/course.html, lms/www/courses/course.js
The Course Description and Lesson Body fields will now be markdown fields.
On migration, a patch will run to convert all markdown content to HTML for the Text Editor.
=> feat: Text editor for course description and Lesson Content

lms/overrides/user.py, lms/www/people/index.html
Guest users will no longer be able to search the people page.
=> fix: don't allow guest users to search the people page

lms/lms/workspace/lms/lms.json, lms/www/courses/create.py, lms/www/courses/outline.py, lms/www/utils.py
1. Fixed course creation URL in the workspace.
2. Added LMS Settings in the workspace.
3. Redirect to the course list page when the course URL is wrong for course creation, outline, and lesson creation.
=> fix: course creation url in LMS

lms/hooks.py, lms/lms/utils.py, lms/public/css/style.css, lms/public/js/website.bundle.js, lms/templates/lms_base.html
1. Client-side telemetry events were not getting captured
2. This was because the Posthog info was not getting set in the boot on the client side.
=> fix: telemetry capture on client side

lms/overrides/test_user.py, lms/overrides/user.py, lms/page_renderers.py, lms/public/css/style.css, lms/www/profiles/profile.html
1. There were way too many restrictions on usernames.
2. If the app was installed on an existing site, and the users in the site had username set that did not meet these restrictions, validation messages are used to pop up on saving the user.
3. This behavior was confusing as there were no such issues before the app was installed.
4. This PR removes all such restrictions.
5. There will only be a few checks on the username. Username should not contain space and the username cannot be duplicated.
6. All other restrictions and validations have been removed.
=> fix: remove space from username

lms/www/batch/learn.js
On creating the quiz, if the first question is of type User Input, the check button was not getting enabled. If the subsequent question is of type User Input, the check button works well.
=> fix: possible answer check

lms/plugins.py, lms/www/batch/edit.js
When adding a video from our computer to the lesson, if the video name had spaces it was not working in the lesson.
Videos with spaces will be accepted in lessons.
Also Fixes: #504
=> fix: embed video with spaces in name

lms/www/courses/create.html, lms/www/courses/create.py
Course Settings are visible to everyone right now
Course Settings will only be visible to moderators
=> fix: show course settings only to moderators

lms/lms/doctype/lms_quiz/lms_quiz.py, lms/www/batch/edit.js
When adding a quiz to a lesson, the dialog previously showed a link field. The dialog will now show a list of quizzes instead. Also, clear instructions on how to add a new quiz have been added.
https://github.com/frappe/lms/assets/31363128/c76244f1-88a4-4225-8aa9-7f719a2bbeb6
=> fix: quiz list in dialog

lms/lms/doctype/work_experience/work_experience.json
On entering work experience in the profile web form, it was throwing an error for **To Date**. But the field was not visible to users.
Both the **To Date** and **Currently Working here** fields will be visible to users now.
=> fix: profile web form

cypress/e2e/course_creation.cy.js, lms/lms/doctype/lms_quiz/lms_quiz.json, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/lms/doctype/lms_quiz_question/lms_quiz_question.json, lms/plugins.py, lms/public/css/style.css, lms/templates/quiz/quiz.html, lms/templates/quiz/quiz.js, lms/www/batch/quiz.html, lms/www/batch/quiz.js, lms/www/batch/quiz.py
1. While creating a quiz, there will now be two additional settings both from the desk as well as LMS Portal.
2. Show Answers: If this is enabled, the quiz will show users answers after each question. 
3. If this is disabled the quiz will directly move to the next question. This setting will be enabled by default.
4. Show Submission History: If this is enabled, then a user will be able to see a summary of their previous submissions below the quiz. This setting is disabled by default.
https://github.com/frappe/lms/assets/31363128/ad289995-5946-4956-bbe8-09570ec7badb
=> feat: show and hide quiz answers

lms/lms/utils.py
instructors = frappe.get_all(
"Course Instructor", {"parent": course}, ["instructor"], order_by="idx"
)
it return like
[
{"instructor": "user1"},
{"instructor": "user2"}
]
and the
if not instructors:
instructors = frappe.db.get_value("LMS Course", course, "owner").split(" ")
return ["user1", "user2"]
and it make error if get all return []
because instructor.instructor at  https://github.com/frappe/lms/blob/main/lms/lms/utils.py#L167
=> fix: course when instructor is not set

lms/lms/doctype/lms_batch/lms_batch.py, lms/patches.txt, lms/patches/v1_0/change_naming_for_batch_course.py, lms/www/batches/batch_details.js
On adding new courses to a batch, an error was thrown
A patch will run that will add a sequence for Batch Course if not already present and will set the next value to 500.
=> fix: batch course sequence id issue

lms/www/courses/create.js, lms/www/people/index.js
Sanitized inputs in these places:
1. After more results are loaded for the people's page.
2. Tags during course creation input.
=> fix: sanitized inputs for people and course creation page

lms/hooks.py, lms/plugins.py, lms/www/batch/edit.js, lms/www/batches/batch.py
You can now add audio files to your lesson. 
https://github.com/frappe/lms/assets/31363128/be543ec4-6547-4115-b7c7-78cba774e5b8
Previously, on adding a video file, the lesson showed a download option. This will no longer be shown.
=> feat: audio in lessons

lms/lms/doctype/lms_batch/lms_batch.js, lms/lms/doctype/lms_batch_timetable/lms_batch_timetable.json, lms/www/batches/index.py
1. The timetable template will now have a Day field. You can add a day for all rows of the template. Based on this day, the dates in the actual timetable get populated.
2. The timetable template also has a duration field. So in case you don't add an end time, the end time in the timetable gets populated based on the duration in hours.
=> feat: Days and Duration in timetable template

lms/lms/doctype/batch_student/batch_student.json, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_settings/lms_settings.json, lms/templates/emails/batch_confirmation.html
Students will now receive an email when they are enrolled in a batch.
You can also set a custom email template from LMS Settings.
=> feat: batch registration confirmation email

lms/www/batch/edit.html
LMS used the latest version of the paragraph plugin of Editor JS.
Due to some recent changes, it has stopped working.
So I have bumped down the version to 2.10
=> chore: bumped down paragraph plugin of editor js

lms/lms/doctype/lms_batch/lms_batch.js, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_batch_timetable/lms_batch_timetable.json, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/lms/doctype/lms_quiz_submission/lms_quiz_submission.json, lms/lms/doctype/lms_quiz_submission/lms_quiz_submission.py, lms/www/batches/batch.js, lms/www/utils.py
Timetable rows can now be marked as milestones. Milestone means that a student will have to complete all previous activities before they can attempt the milestone activity.
=> feat: timetable milestones

lms/www/batches/batch.js
1. When a student is scheduling an evaluation and they change the course in the schedule dialog, the date and the slots already selected will revert back to an empty state now.
2. This also fixes the issue of wrong slots appearing.
=> fix: evaluation slots

lms/install.py, lms/lms/doctype/batch_student/batch_student.json, lms/lms/doctype/lms_payment/lms_payment.json, lms/lms/doctype/lms_source/lms_source.js, lms/lms/doctype/lms_source/lms_source.json, lms/lms/doctype/lms_source/lms_source.py, lms/lms/doctype/lms_source/test_lms_source.py, lms/lms/utils.py, lms/patches.txt, lms/patches/v1_0/create_batch_source.py, lms/www/billing/billing.js
The billing flow now has a source field where a student can select the source through which they got to know about the batch or course.
This source information will be saved in the LMS Payment and LMS Batch Student doctype.
src="https://github.com/frappe/lms/assets/31363128/25cb6b95-6488-425d-82c0-2cdb5c6c45d9">
#638
=> feat: batch source

lms/lms/doctype/lms_batch/lms_batch.py
fix: typeError in validate_timetable
getting error :- TypeError: '<' not supported between instances of 'str' and 'datetime.timedelta'
Possible source of error: mb_fxlh (app)
Used case :- Adding row in lms batch timetable from other doctype:
=> Fix:timetable validation

lms/lms/doctype/lms_settings/lms_settings.json, lms/patches.txt, lms/patches/v1_0/batch_tabs_settings.py, lms/patches/v1_0/create_batch_source.py, lms/www/batches/batch.html, lms/www/batches/batch.py
LMS settings now have batch tabs settings where you can decide which tabs to show on the batch page. By default all the tabs are visible, disabling these will remove the tabs from the batch page.
=> feat: batch tabs settings

lms/templates/certificates_section.html
Profile page used to show wrong certificates on the profile page. It used to show the session users certificates instead of the profile users.
Profile page will now show the profile users certification.
=> fix: certificates in profile

lms/www/courses/course.py
After a user completes a course and the course has certification enabled, the Get Certificate button is not visible.
The button will now be visible.
=> fix: get certificate button visibility

lms/lms/doctype/lms_batch/lms_batch.json, lms/public/js/common_functions.js, lms/www/batches/index.html, lms/www/batches/index.py
If a batch starts this afternoon, then the batch does not appear in the upcoming batch list from today morning itself. The filters only consider the start date and not the start time. This prevents students from registering a batch even though a few hours are left before it starts.
A batch will be shown in the upcoming tab till its start date has passed.
=> fix: upcoming batches based on start time

lms/www/batch/edit.html, lms/www/batch/edit.js
If the chapter name has special characters then it creates issues while adding a lesson to it.
Encoding the chapter name solves the issue.
=> fix: encode chapter during lesson creation

lms/lms/utils.py
Users with Course Creator roles faced an issue while creating a new course.
https://github.com/frappe/lms/assets/31363128/204b7d77-f0d0-40e2-9294-e36981d312cb
Now if a new course is being created it will check if the user has course creator role and allow them to proceed.
=> fix: course creation issue

lms/hooks.py, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_payment/lms_payment.js, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/lms/utils.py, lms/templates/emails/mention_template.html, lms/templates/quiz/quiz.html, lms/templates/quiz/quiz.js, lms/www/quiz_submission/quiz_submission.py
1. Now when a moderator gets tagged in a discussion they will receive an email informing them about the same.
2. In LMS Payments doctype you can now add website users as members too.
3. Fixed quiz working from submission page.
=> feat: misc changes

lms/lms/doctype/lms_batch/lms_batch.js, lms/public/css/style.css, lms/www/batches/batch.js, lms/www/batches/batch_details.py
Moderators can now add All Day events to the timetable. If you want to make an all-day event, don't set the start and end times for such events.
=> feat: all day events

lms/public/css/style.css, lms/www/batches/batch.js
The event title was not visible in the timetable for all-day events. Only start and end time was visible. This gave no idea to students and moderators about the activity unless they hovered over it.
Now the title of the activity will be visible for all day events.
=> fix: All day events style

lms/www/batches/batch.html, lms/www/batches/batch.js
1. When Allow Future Dates were unchecked in a batch, even moderators and instructors were not allowed to access activities from future dates.
2. Milestones were being checked for moderators and instructors too.
1. Now even if Allow Future Dates is unchecked, moderators will be allowed to access future activities.
2. Milestones will only be checked for students now.
=> fix: future date access on timetables for moderators

lms/lms/doctype/lms_settings/lms_settings.json, lms/public/css/style.css, lms/www/batches/batch.html, lms/www/batches/batch.js
On smaller screen sizes, the timetable will have a day view now.
There is also a configuration in LMS Settings now where you can enable day view as default for all screens.
If this is enabled the timetable will have a day view even on desktops.
=> feat: day view for timetable on mobile

lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.json, lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.py
1. Rating field in evaluation doctype will only be mandatory if the status is Pass or Fail.
2. The summary field will also be mandatory now if the status is Pass or Fail.
=> fix: evaluation fields

lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.py
When a user completes the assignment an email gets triggered to all the moderators. If Administrator has the role of moderator, it gives an error as its not a valid email.
Before the email is sent the recipient email addresses will be validated.
=> fix: assignment issue

lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_course/lms_course.json, lms/lms/utils.py, lms/public/js/common_functions.js, lms/www/batches/batch_details.py, lms/www/batches/index.py, lms/www/billing/billing.py, lms/www/courses/course.py, lms/www/courses/index.py
1. LMS Batch and LMS Course will now have a separate field for USD pricing. 
2. If a value is set here then to all countries except the exception country will be shown this USD amount.
3. If a value is not set here and Show USD Equivalent is checked in LMS Settings then the USD amount will be shown based on calculations.
=> feat: usd pricing

lms/lms/notification/certificate_request_reminder/certificate_request_reminder.json
=> fix: remove $ typos

lms/lms/doctype/batch_student/batch_student.py, lms/lms/doctype/lms_batch/lms_batch.json, lms/www/batches/batch_details.html, lms/www/batches/batch_details.js, lms/www/batches/batch_details.py
1. Moderators can now allow students to self-enroll themselves into unpaid batches.
2. Just enable the option Allow Self Enrollment for the batch.
3. If this option is enabled, students will see a button **Enroll Now**, on the batch details page.
4. Clicking this button will enroll them into the batch.
=> feat: self enrolment in batches

lms/www/batches/batch.html, lms/www/batches/batch_details.html, lms/www/batches/index.html
Closes #721 
Also, while working on this I realise icon alignment is broken, but since the new revamp is coming, I let it be @pateljannat
=> fix: only show start date for single day batches

frontend/src/components/Modals/EvaluationModal.vue
1. When there are it slots available on a day, it wasn't being indicated properly.
2. Now a proper message will be shows informing students that no slot is available in that day.
=> fix: no slots message

frontend/src/components/LessonPlugins.vue, lms/job/doctype/lms_job_application/lms_job_application.py, lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.py, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_certificate/lms_certificate.py
1. Before an email is sent when a certificate is created or when a student is added to a batch, the outgoing email account gets checked.
2. The email gets sent only if an outgoing email account exists.
3. This causes problems for sites that have email configured through site config.
4. So now before sending an email, site configuration will also be checked.
=> fix: check site conf before sending email

frontend/src/pages/Lesson.vue
Probably not the best fix, but works for now. EditorJS mounting etc. needs a refactor to be in the Vue world @pateljannat
=> fix: editor holder not cleaned up

frontend/src/components/Modals/LiveClassModal.vue, frontend/src/components/Quiz.vue, frontend/src/components/QuizBlock.vue, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_quiz/lms_quiz.json
1. You can now allow shuffling of quiz questions.
2. For this, check the Shuffle Quiz option when creating a quiz.
3. When this option is enabled, quiz questions will appear in random order for each user.
=> feat: quiz shuffle

frontend/src/components/Quiz.vue
Problem:
`attempts` resource was only getting reloaded onSuccess of quiz. But since `quiz` is cached, onSuccess does not run again on remount of the quiz (try switching between lessons). This results in max attempts exceeded message.
Solution: 
Reload attempts whenever quiz data changes
=> fix: quiz attempts load issue

frontend/src/components/CourseCardOverlay.vue, frontend/src/components/Quiz.vue, frontend/src/components/UserDropdown.vue, frontend/src/pages/CreateCourse.vue, frontend/src/pages/Lesson.vue, frontend/src/pages/ProfileEvaluator.vue, lms/lms/doctype/lms_quiz_result/lms_quiz_result.json, lms/lms/notification/certificate_request_reminder/certificate_request_reminder.html
Fixes #823 and #820 
Also changes User Response field from Data to Small Text in LMS Quiz Submission to accommodate bigger responses
=> fix: edit permission and other issues

frontend/src/components/CourseCard.vue, frontend/src/components/CourseOutline.vue, frontend/src/pages/CertifiedParticipants.vue, frontend/src/pages/Courses.vue, frontend/src/pages/CreateCourse.vue, frontend/src/pages/Statistics.vue, frontend/src/utils/index.js, lms/lms/api.py, lms/lms/doctype/lms_course/lms_course.json, lms/lms/utils.py, lms/public/frontend/index.html, lms/www/lms.py
You can now feature courses based on your choice. To feature a course, just enable the checkbox when creating or editing the course. 
All featured courses will appear at the top of the Live section with a badge indicating the same. The rest of the courses will appear after them.
=> feat: featured courses

frontend/src/components/UserDropdown.vue, frontend/src/pages/Badge.vue, frontend/src/pages/ProfileAbout.vue, frontend/src/router.js, frontend/src/stores/session.js, lms/lms/doctype/lms_badge/lms_badge.json, lms/public/frontend/index.html, lms/www/lms.py
Learners will now be able to share their badges on LinkedIn and Twitter. To share, they just have to visit their profile page and hover over the badge. In the Popover they will see the share icon. Clicking on the icon redirects them to the platform with the message in the post modal.
https://github.com/frappe/lms/assets/31363128/2f471bb0-d15a-4163-b8b5-e138ace8be1c
=> feat: share badge on linkedin

frontend/src/components/Modals/EvaluationModal.vue, frontend/src/pages/ProfileEvaluator.vue, lms/lms/doctype/course_evaluator/course_evaluator.py, lms/lms/doctype/lms_certificate_request/lms_certificate_request.py
1. Learners were unable to schedule an evaluation for the current date even if the slot time has not yet passed.
2. Evaluators were getting an error when setting their unavailability from their profile.
=> fix: evaluation related issues

frontend/src/components/Modals/LiveClassModal.vue
FrappeUI's Dialog component automatically showa a loading indicator on Action if it is a promise.
=> fix: show loading indicator while live class creation

lms/lms/doctype/lms_certificate_request/lms_certificate_request.js, lms/lms/doctype/lms_certificate_request/lms_certificate_request.py
I have added a button on LMS Certificate Request to generate a Google Meet link. This button will only be visible if the Google Meet link is not present.
=> fix: event meeting generation

frontend/src/components/Controls/IconPicker.vue, frontend/src/pages/CreateCourse.vue, lms/lms/doctype/lms_certificate_request/lms_certificate_request.js, lms/public/frontend/index.html
The validation messages when creating a new course were not clear.
Made the message clear now
=> fix: better validation message on course creation

cypress.config.js, cypress/e2e/course_creation.cy.js, frontend/src/components/AudioBlock.vue, frontend/src/components/VideoBlock.vue, frontend/src/stores/user.js, frontend/src/utils/customEmbed.js, frontend/src/utils/index.js, frontend/src/utils/upload.js, lms/public/frontend/index.html
Audio and Video used the default HTML5 format. This was very inconsistent throughout browsers. 
**Chrome**
**Firefox**
**Safari**
Created components to make this consistent across browsers.
https://github.com/frappe/lms/assets/31363128/9c7a6678-aa72-41cc-b85b-d98d18f75bb5
=> feat: video and audio player

frontend/src/utils/index.js
The following sources can now be embedded into lessons:
1. Videos from Google Drive: https://drive.google.com/file/d/some-id/view?usp=drive_link\
---
2. Google Docs: https://docs.google.com/document/d/some-id/edit?usp=sharing
---
3. Google Sheets: https://docs.google.com/spreadsheets/d/some-id/edit?usp=sharing
---
4. Google Slides: https://docs.google.com/presentation/d/some-id
---
5. Codesandbox: https://codesandbox.io/embed/some-id?view=editor+%2B+preview&module=%2Findex.html
---
6. Google Gist: https://gist.github.com/username/some-id
NOTE: All the above URLs are just examples of the format. For google suite embeds if the user does not have permission to that document the content will not be visible to them.
=> feat: more embed sources for lesson components

frontend/src/components/Quiz.vue, lms/hooks.py, lms/lms/doctype/lms_quiz/lms_quiz.json, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/lms/doctype/lms_settings/lms_settings.json, lms/lms/utils.py, lms/overrides/user.py, lms/plugins.py
You can now limit the number of questions to be shown in a quiz. So if a quiz has 10 questions and you want the students to attempt only 5 questions, you can set it as the limit. Students will then only see the first 5 questions when attempting the quiz.
If the Shuffle Questions setting is also enabled then students will see random 5 questions from the total questions in the quiz. Also based on the limit, the total marks get calculated for the quiz.
=> feat: limit questions in quiz

lms/hooks.py
Course cards fails to render on home page.
=> fix: course cards home page rendering

frontend/src/components/Quiz.vue, lms/lms/doctype/lms_quiz/lms_quiz.py
1. If the quiz had shuffle enabled, the quiz submission was showing wrong questions against user responses.
2. The user responses are all in the correct order as per the shuffle, but the questions are in the order that they were in the quiz. So the response does not match with the question.
=> fix: quiz submission report issue

lms/overrides/user.py
Support ticket #20855, #20873
User's notifications settings get created in User after_insert hook, which isn't called in this case
=> fix(overrides): call parent's `after_insert()` as well

frontend/src/utils/index.js
1. Google Slides was not getting rendered in lessons.
2. Fixed the regex to resolve the issue.
=> fix: slides rendering issue

lms/public/css/style.css
Removed a cursor as none and added it as pointer 
we could not be able to see a cusrsor
[Screencast from 02-09-24 03:15:26 PM IST.webm](https://github.com/user-attachments/assets/05c6770c-d1ab-41d7-b556-f530e9348e64)
=> feat: added a cusrsor

lms/lms/doctype/lms_batch/lms_batch.py
1. Batch enrollment confirmation email used to get triggered on batch validation.
2. If in case it did not trigger when the student got enrolled and the next time an enrollment happened was months later, the previous student would receive the email then.
3. This causes confusion as they had registered months ago.
4. To prevent this, the condition now checks if the user was enrolled within the last 2 days, only then does the email get triggered.
=> fix: batch confirmation email trigger

frontend/src/components/Assessments.vue, frontend/src/components/Quiz.vue, frontend/src/pages/QuizSubmission.vue, frontend/src/router.js
1. Quizzes can now be a separate page. Moderators wanting to run quizzes independently can use this page and share the URL with the participants.
2. This page will also open up when a quiz is added as an assessment in any batch.
=> feat: quiz page

frontend/src/components/Modals/ExplanationVideos.vue
Issue: The URLs of the lesson help videos were not working.
Fix: Changed them to /assets/lms/frontend/.. to make it work.
=> fix: url for lesson help videos

frontend/src/components/Modals/EvaluationModal.vue
When a student tried scheduling an evaluation after the Evaluation End Date, the error message was not visible. There was an error in the console.
=> fix: evaluation error message issue

frontend/src/components/Assessments.vue, frontend/src/components/LessonContent.vue, frontend/src/utils/upload.js, lms/lms/doctype/course_lesson/course_lesson.json
1. PDF rendering doesn't work on mobile as mobile browsers don't support the same.
2. This is an experiment to see if using google docs PDF viewer makes the content work in mobile.
=> fix: using google docs viewer to render pdf

frontend/src/components/LiveClass.vue
1. Live class start button should only be visible to Moderators and Evaluators.
=> fix: show live class start button only to moderators and evaluators

lms/lms/report/course_progress_summary/course_progress_summary.py
This is a small logical fix.
Otherwise if `row.progress == 10 or row.progress == 40 or row.progress == 70` wouldn't have an effect.
=> fix: small bug in course_progress_summary.py

frontend/package.json, frontend/src/components/Controls/MultiSelect.vue, frontend/src/pages/CourseForm.vue, frontend/yarn.lock
Closes #1026 
- Add required indicator on the course add page
=> feat: add required indicator on the course add page

frontend/src/components/Modals/EvaluationModal.vue, frontend/src/pages/BatchForm.vue, frontend/src/pages/CourseForm.vue, lms/lms/utils.py
1. For a batch, multiple courses are linked.
2. You may not want to evaluate your students for all the courses.
3. So now, only courses that have an evaluator set in the batch will be available for evaluation.
=> fix: show only courses with evaluator for batch evaluation

frontend/src/pages/Jobs.vue
Closes #845 
- Added search and filtering functionality in the Jobs, enabling search by Title, Location, Company Name, and Job Type.
https://github.com/user-attachments/assets/b32c0d59-daf7-40fe-963c-138439b2c70f
=> feat: search functionality in jobs

frontend/src/components/AppSidebar.vue, frontend/src/components/Modals/ChapterModal.vue, frontend/src/components/Modals/Question.vue, frontend/src/pages/Courses.vue, frontend/src/pages/QuizForm.vue, frontend/src/pages/SCORMChapter.vue, lms/lms/doctype/lms_question/lms_question.py
1. Removed focus from chapter title field in chapter modal.
2. Instructors were unable to see the new course creation button. They can now see the button with this fix.
3. Minimum 2 options for choices were not getting validated.
=> fix: misc issues

frontend/src/components/Modals/LiveClassModal.vue, frontend/src/utils/dayjs.js
Closes #1063 
- Allow users to create live classes on the same date with a future time, ensuring that the class time is validated relative to the selected timezone.
- Imported `timezone` and `utc` plugins from `dayjs` to handle timezone conversions and comparisons.
- Updated course time validation to ensure the class time is in the future based on the selected timezone, rather than comparing it with the system's local time.
=> feat: allow same date live class creation

frontend/src/pages/LessonForm.vue
Closes #1121 
- Users can now save a lesson using a shortcut.
-  A toast message will appear when a lesson is saved manually.
- The toast message will be hidden when the lesson is auto-saved.
=> feat: add keyboard shortcut to save lesson

frontend/src/components/SidebarLink.vue
Closes #1043 
- Show the notification count at the top in collapsed mode when it is greater than 9.
https://github.com/user-attachments/assets/babd2fbc-9482-4615-ba5c-77d793790e8c
=> fix: show notification count at the top in collapsed

frontend/src/components/DesktopLayout.vue, frontend/src/components/Modals/ChapterModal.vue, frontend/src/components/OnboardingBanner.vue, frontend/src/pages/CourseForm.vue, frontend/src/pages/LessonForm.vue, frontend/src/stores/settings.js, lms/lms/utils.py
https://github.com/user-attachments/assets/f4a80f79-c1ce-4250-af4e-edae20bbc35b
1. On a brand new site, Moderators will now see onboarding steps.
2. They can skip the onboarding if they already know their way around, and that would hide the banner forever.
3. But if they don't have experience with the system, they can follow the steps.
4. The steps are simple: create a course, create a chapter, then create a lesson.
5. The first step is enabled, and the other two are disabled.
6. Clicking on the first steps takes them to the course form. When they create the course, the first step gets completed, and the second step becomes active.
7. Clicking on the second step takes them to the course form of the first course in the system. There, they need to add a chapter. When they do so, the second …
=> feat: onboarding steps

frontend/src/components/Modals/Question.vue, frontend/src/pages/JobCreation.vue, frontend/src/pages/QuizForm.vue
- Add the required indicator to the Jobs and Quiz forms for fields that are missing.
=> feat: add required indicator in jobs and quiz

frontend/src/pages/SCORMChapter.vue, lms/hooks.py, lms/lms/api.py, lms/page_renderers.py
=> refactor: scorm package render

frontend/src/components/Assessments.vue, frontend/src/components/BatchCourses.vue, frontend/src/components/BatchStudents.vue, frontend/src/components/Modals/StudentModal.vue, frontend/src/pages/BatchForm.vue, lms/lms/utils.py
On the batch page, Moderators and Evaluators will now be able to see the progress students have made in the courses and assessments linked to that batch.
=> feat: show student course and assessment progress on batch page

frontend/src/pages/LessonForm.vue, frontend/src/utils/index.js, frontend/src/utils/markdownParser.js
1. Markdown links were not working. Enabled inlineToolbar for Paragraph plugin to fix the issue.
=> fix: markdown parser link issue

frontend/src/components/BatchStudents.vue, frontend/src/components/LiveClass.vue, lms/lms/utils.py
1. Fixes #1225 
2. Fixes #1217 
3. Progress percentage will now be visible in batches on the students' list. The list will be sorted based on descending order of progress.
=> fix: misc batch issues

frontend/src/components/Assessments.vue, frontend/src/components/BatchDashboard.vue, frontend/src/components/BatchStudents.vue, frontend/src/components/Modals/BatchStudentProgress.vue, frontend/src/components/StudentHeatmap.vue, frontend/src/components/UpcomingEvaluations.vue, frontend/src/pages/Batch.vue, frontend/src/pages/Programs.vue, frontend/src/utils/theme.js, frontend/vite.config.js, lms/lms/api.py
1. Students can now see their activities for the last 30 weeks as a heat map on the batch dashboard.
2. The admins can see the same on their batch dashboard, in that students progress modal.
=> feat: student activities display in a heatmap

lms/lms/api.py
- Latest Develop branch causes Internal Server Error due to incorrect python import.
- It should be `date_diff` instead of `days_diff` in frappe.utils.data
=> fix: fixed typo in spelling in frappe.utils.date_diff import

frontend/src/pages/Batches.vue, frontend/src/pages/Courses.vue, frontend/src/pages/Lesson.vue, frontend/src/pages/LessonForm.vue, frontend/src/stores/settings.js, frontend/src/utils/index.js, frontend/tailwind.config.js, lms/lms/utils.py
1. Format lists and tables in the lesson editor.
2. The course list is now responsive for huge screen sizes too. #1124
3. Settings network calls won't break for guest users now.
4. Batch category filter wasn't working, will start working with this PR
=> fix: made course list responsive for bigger screen sizes

frontend/src/components/BatchFeedback.vue, frontend/src/components/Modals/EditProfile.vue, frontend/src/utils/index.js, lms/lms/doctype/lms_batch_feedback/lms_batch_feedback.json
1. Batch Feedback will have parameters for Content, Instructor, and Value. It will no longer have the delivery parameter.
2. Before saving the profile bio, sanitized its value to escape scripts.
=> fix: removed delivery parameter from batch feedback

frontend/src/pages/Batches.vue, lms/lms/utils.py
The previous implementation of the batch list was not good for scale. Now with time, as most platforms have too many batches, loading them all slowed down the system. The previous design also restricted the improvements.
This PR refactors the entire batch list both for performance and UI. There are better filters on the page that load data accordingly ensuring that the system is not loaded.
https://github.com/user-attachments/assets/a89a2e78-99db-442c-98a4-d0a9198b971e
=> refactor: improved performance and ui batch list

lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_course/lms_course.py
Previously, batch names were in the format of CLS-####. This was not URL-friendly. This PR changes the batch name to a slug. For example, if a batch's title is Framework March 2025, then the batch's name would be framework-march-2025. This would give some context of the batch when the URL is shared.
Closes #733
=> refactor: changed batch naming to be a slug of the title

frontend/src/components/DiscussionReplies.vue, frontend/src/main.js, frontend/src/pages/Notifications.vue, frontend/src/router.js, frontend/src/stores/session.js, lms/lms/api.py, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/doctype/lms_course_progress/lms_course_progress.json, lms/lms/utils.py, lms/lms/web_template/courses_enrolled/courses_enrolled.html
1. Added indexes for LMS Course Progress
2. The allUsers function was a risk, so now only the Moderator, Course Creator, and Batch Evaluator can access this role. Its usage is only for mentions, so only these roles can use the mention functionality in discussions. Others can just send messages.
=> perf: misc performance improvements

frontend/src/components/AppSidebar.vue, frontend/src/stores/sidebar.js
Stores the Sidebar states in localStorage so that it does not get reset on refresh.
[Current Sidebar on Refresh](https://github.com/user-attachments/assets/0d64e100-c36d-4c6c-aba7-6c303b971e67
)
[New Sidebar on Refresh](https://github.com/user-attachments/assets/eda509df-99c9-459e-8542-283cbf91ad6e)
=> ui: added persistent Sidebar Collapsibility and Sidebar Webpages

frontend/src/components/Modals/ChapterModal.vue, frontend/src/components/Modals/Settings.vue, frontend/src/pages/CourseForm.vue, frontend/src/pages/LessonForm.vue, frontend/src/router.js, frontend/src/stores/settings.js, lms/lms/api.py, lms/lms/doctype/lms_settings/lms_settings.json, lms/patches.txt, lms/patches/v2_0/allow_guest_access.py
1. Some of the pages of the system are accessible to Guest users as well, like course and batch list, etc.
2. Some organizations that create content for a very specific audience may not want to show even these details to guest users.
3. So now, admins of the system can configure if they want to allow guest users to access the system. This would be enabled by default but can be turned off from the Settings dialog.
Closes #490
Closes #1023
=> feat: configuration to allow guest access

frontend/index.html, frontend/src/components/AppSidebar.vue, frontend/src/components/Modals/FCVerfiyCodeModal.vue, frontend/src/components/UserDropdown.vue, frontend/vite.config.js, lms/lms/api.py, lms/www/lms.py
1. Sites hosted on Frappe Cloud will now be able to login to their Frappe Cloud dashboard right from the Learning portal.
2. Trial Sites on Frappe Cloud, will see a banner informing them of their trial details with an option to upgrade the plan.
=> feat: billing banner for FC trial sites

frontend/src/pages/BatchForm.vue, lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_batch_enrollment/lms_batch_enrollment.py
1. Previously, when a student gets enrolled in a batch, the system sends a standard email confirming their enrollment. 
2. Admins can override this by creating a new email template and linking it to the Batch Confirmation Template field in LMS Settings.
3. But what if admins want to send different emails for different batches?
4. To solve this problem, now each batch has a Confirmation Email Template field. If a template is added here, this template will be used for this batch.
=> feat: batch specific email templates

frontend/src/components/Quiz.vue, frontend/src/pages/QuizForm.vue, frontend/src/router.js, frontend/src/utils/quiz.js, lms/lms/doctype/lms_quiz_submission/lms_quiz_submission.py, lms/locale/ar.po, lms/locale/bs.po, lms/locale/de.po, lms/locale/eo.po, lms/locale/es.po, lms/locale/fa.po, lms/locale/fr.po, lms/locale/hu.po, lms/locale/main.pot, lms/locale/pl.po, lms/locale/ru.po, lms/locale/sv.po, lms/locale/tr.po, lms/locale/zh.po
This PR includes
- Validation for quiz submission limit (both in backend and frontend)
- Fixed some spelling typos
- Fixed an issue while running yarn dev
Closes #1314
=> fix: fixed bug in which user can submit quiz over the maximum limit allowed

frontend/src/pages/Batch.vue, frontend/src/pages/BatchForm.vue, frontend/src/pages/Batches.vue, lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_payment/lms_payment.json, lms/lms/utils.py
1. Admins can now mark batches for certification.
2. Such batches can then be filtered from the batch list.
https://github.com/user-attachments/assets/db27c751-fa77-42eb-aa4b-8074e6e0a9a8
=> feat: filter certification batches

frontend/src/components/UpcomingEvaluations.vue, lms/lms/api.py, lms/lms/doctype/lms_certificate_request/lms_certificate_request.json, lms/lms/utils.py, lms/patches.txt, lms/patches/v2_0/update_certificate_request_status.py
Students can now cancel an evaluation from the portal. They can do so till a day before the evaluation is scheduled.
=> feat: cancel evaluations

lms/hooks.py, lms/lms/doctype/lms_certificate_request/lms_certificate_request.py
There will be a Scheduler Event that runs every hour. It will check for all upcoming evaluation requests that have ended and mark its status as Completed.
=> feat: mark evaluation requests as complete

lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.js, lms/lms/doctype/lms_certificate_request/lms_certificate_request.js, lms/lms/doctype/lms_certificate_request/lms_certificate_request.py
If a student has canceled an evaluation and was later trying to reschedule, they received a validation message stating that they already have an eval scheduled in the future, even though that eval has been canceled.
1. Only consider evals with the status Upcoming when validating for already scheduled evals.
2. Don't show buttons to Generate Meet Link and Conduct Eval from the desk form.
=> fix: allow scheduling evals if future eval has been cancelled

lms/page_renderers.py
SCORM packages created from 360 learning were not being rendered when hosted on production. Some of the files, that were mentioned with a relative path were taking the wrong path.
=> fix: scorm files getting wrong path

frontend/components.d.ts, frontend/src/components/Modals/Question.vue, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/doctype/lms_quiz/lms_quiz.json, lms/lms/doctype/lms_quiz/lms_quiz.py
When a quiz was added to a lesson, lesson details were not saved in the quiz. Because of this, the lesson was not marked complete, as its details were missing from the quiz.
Lesson details are now being saved in the quiz, when it is added to a lesson.
=> fix: save lesson details in quiz

cypress/e2e/course_creation.cy.js, frontend/src/components/BatchOverlay.vue, frontend/src/components/Modals/Settings.vue, frontend/src/components/SettingDetails.vue, frontend/src/components/SettingFields.vue, frontend/src/pages/BatchDetail.vue, lms/lms/doctype/lms_settings/lms_settings.json, lms/www/lms.py
You can now add Meta Image and Keywords in SEO settings.
This image and keywords will be used on pages that don't have an image by default.
Also closes #1418
=> feat: meta image and keywords from settings

frontend/src/components/CourseCard.vue, frontend/src/pages/CourseDetail.vue, frontend/src/utils/index.js
1. Allow Fullscreen for Vimeo.
2. The video height was broken on mobile devices.
It's fixed now,
=> fix: allow fullscreen on vimeo and adjust video height on mobile devices

lms/lms/utils.py, lms/lms/widgets/CourseCard.html
Previously, when fetching instructors, only the parent was looked for. This caused an issue with courses and batches having the same name. So now, when fetching instructors, the parent type will also be checked.
=> fix: check parenttype when fetching instructors

frontend/src/components/CourseCardOverlay.vue, frontend/src/pages/Lesson.vue, lms/lms/utils.py
Students were able to enroll for a course even if self-enrollment was disabled. This was because the Start Learning button was still shown in the Lesson.
=> fix: hide start learning button if self enrollment is disabled

frontend/src/pages/Lesson.vue, frontend/src/utils/index.js
Now that we use Plyr on top of YouTube and Vimeo embeds, this was working well for one video, but if a lesson has more than one video, only one video was visible.
This PR makes Plyr work for all embeds in a lesson.
=> fix: plyr will now work on all videos of a lesson

frontend/components.d.ts, frontend/src/components/BrandSettings.vue, frontend/src/components/Categories.vue, frontend/src/components/EmailTemplates.vue, frontend/src/components/Modals/EmailTemplateModal.vue, frontend/src/components/Modals/Settings.vue, frontend/src/components/PaymentSettings.vue, frontend/src/components/SettingFields.vue, frontend/src/pages/BatchForm.vue
You can now create and edit Email Templates from the frontend
<hr>
=> feat: email template in settings

frontend/src/components/Modals/EditProfile.vue
This pr contains following :- 
1. Fix html render issue in profile > about 
Currently about section of the profile does not show bio correctly
https://github.com/user-attachments/assets/a74d9121-4d0c-4804-af82-e9e4e0210e83
A simple fix is to remove the escapeHtml when saving
Since **Tiptap** automatically outputs safe HTML we don't need to use **escapeHtml**, below are the screenshots if user tries to use **JS**
=> fix: Edit profile escape html

frontend/src/components/Modals/Event.vue, frontend/src/components/UpcomingEvaluations.vue, frontend/src/pages/Batch.vue, frontend/src/pages/Notifications.vue, frontend/src/pages/ProfileEvaluationSchedule.vue, lms/lms/doctype/lms_certificate_request/lms_certificate_request.py
1. Don't show cancelled requests on the evaluator's calendar.
2. Show Schedule Evaluation button if the number of upcoming evaluations is not equal to the number of courses that need evaluations.
=> fix: misc evaluation issues

lms/lms/utils.py
The course and Batch lists were only fetching 20 records, even though the page length was being passed as 30. The default parameter of page length was set as 20 and it was overriding the value passed from frontend
=> fix: page length issue on course list

frontend/src/components/Settings/BrandSettings.vue, frontend/src/pages/ProgrammingExercises/ProgrammingExerciseSubmission.vue, frontend/src/pages/ProgrammingExercises/ProgrammingExercises.vue
1. When the logo is updated from brand settings, the login logo is not getting updated. This PR fixes that.
2. Livecode URL will now be picked from settings if set.
=> fix: when logo is updated from brand settings, update the login logo too

cypress/e2e/batch_creation.cy.js, frontend/src/components/Modals/CourseProgressSummary.vue, frontend/src/components/Settings/Evaluators.vue, frontend/src/components/Settings/Members.vue, frontend/src/components/Settings/Settings.vue, frontend/src/pages/Profile.vue, frontend/src/pages/ProfileRoles.vue, lms/lms/api.py, lms/lms/doctype/course_evaluator/course_evaluator.json, lms/lms/notification/certificate_request_reminder/certificate_request_reminder.json, lms/lms/utils.py
1. The member list will no longer show Last Active; instead, it will highlight the primary role of the user if they are not a student
2. The form to add a new member will now open as a dialog
3. The form to add a new evaluator will open as a dialog.
4. Moderators can now also delete evaluators from the list
=> fix: improved members and evaluators list and form

frontend/src/pages/CourseForm.vue
I noticed that while creating a new course, if you add multiple tags the tags would overflow out of the container. And you could not click the close (x) button on these overflowing tags. (see image below)
I have updated it so the tags wrap neatly and don't break the layout.
=> fix: ensure tags wrap correctly to prevent overflow and breaking of layout

frontend/src/pages/BatchForm.vue, frontend/src/pages/CourseForm.vue, frontend/src/pages/JobForm.vue, frontend/src/utils/index.js
While creating a new course, batch or job, I was not able to upload certain photos whenever an image upload was required. This was because the image validation function checks for the file extension and only allows 3 extensions - jpg, jpeg, png. This is quite restrictive and does not allow for many other image types such as svg, tiff, bmp, webp, avif etc. 
Also, file extensions can be spoofed so it is not very secure. A better way would be to check for MIME type. So I have changed the validation to MIME type validation which is more secure and incorporates all types of image files.
Also made a UI change so the user can now click on empty image card to open the Image selector dialog box.
https://github.com/user-attachments/assets/a90148fd-89ac-4d9f-a459-e69a0f5c275d
=> fix: Changed image extension validation to MIME type validation

frontend/src/utils/index.js
Vimeo videos had stopped working because a recent change was considering all embeds as YouTube. Removed the line of code that was setting `data-plyr-provider` as `youtube` for all sources.
=> fix: vimeo video embed with plyr

frontend/src/components/InstallPrompt.vue
Earlier iosInstallMessage on mobile was not set properly it takes too much space on bottom 
https://github.com/user-attachments/assets/0f6c1fbc-bab3-4d9e-b28d-b95ae6f8388c
Now fixed the styling issue it is now sticked above bottom bar
https://github.com/user-attachments/assets/90e20977-e8e2-4772-91ce-f3f4b8c28ac9
=> fix(ui): make install prompt message mobile responsive

frontend/src/pages/Home/Home.vue, frontend/src/pages/Home/StudentHome.vue, frontend/src/pages/Programs/ProgramForm.vue
Text disappears in dark theme. Added text colors to fix it.
closes: #1744
=> fix: make text visible in dark theme

frontend/src/components/AppSidebar.vue, frontend/src/components/Settings/Settings.vue, frontend/src/components/SidebarLink.vue, frontend/src/stores/settings.js, frontend/src/utils/index.js, lms/job/doctype/job_opportunity/job_opportunity.py, lms/lms/api.py, lms/lms/doctype/lms_settings/lms_settings.json, lms/lms/doctype/lms_settings/lms_settings.py, lms/patches.txt, lms/patches/v2_0/certified_members_to_certifications.py
Admins can now add a Contact Us link to the sidebar for settings. This can be an email address on click of which the email pop-up opens, or it can be a link to a separate page that opens in a new tab.
=> feat: contact us
