frappe/lms

community/community/doctype/community_course/community_course.js, community/community/doctype/community_course/community_course.json, community/community/doctype/community_course/community_course.py, community/community/doctype/community_course/templates/community_course.html, community/community/doctype/community_course/templates/community_course_row.html, community/community/doctype/community_course/test_community_course.py, community/community/doctype/community_course_topic/community_course_topic.js, community/community/doctype/community_course_topic/community_course_topic.json, community/community/doctype/community_course_topic/community_course_topic.py, community/community/doctype/community_course_topic/templates/community_course_lession.html, community/community/doctype/community_course_topic/templates/community_course_lession_row.html, community/community/doctype/community_course_topic/test_community_course_topic.py, community/www/courses/course.html, community/www/courses/course.py, community/www/courses/index.html, community/www/courses/index.py, community/www/courses/macros/card.html, community/www/courses/topic.html, community/www/courses/topic.py
- Added "Community Course" doctype
- Added Form Scripts to set the route on first save
- Customized row and view templates
Yet to figure out how to entire course listing page.
Issue #4
=> First cut at the course doctype.

community/community/doctype/community_member/community_member.json, community/community/doctype/community_member/community_member.py, community/community/doctype/community_member/test_community_member.py, community/community/utils.py, community/hooks.py, community/lms/doctype/lms_batch/lms_batch.py, community/lms/doctype/lms_course/test_lms_course.py, community/lms/doctype/lms_message/lms_message.json, community/lms/doctype/lms_message/lms_message.py, community/public/css/style.css, community/www/courses/course.js, community/www/courses/discuss/index.html, community/www/courses/discuss/index.js, community/www/profiles/profile.py
1. Discussions Page for Batch
2. Community Member duplicate name issue on sign up
3. Validations for community member user name
4. Test for validating community member creation from user
5. Tests to verify members with the same full_name
=> fix: Batch discussions and Community Member fixes

README.md, docker-compose.yml
=> feat: dev-instance using docker-compose

community/lms/doctype/invite_request/invite_request.py, community/lms/widgets/RequestInvite.html
=> fix: invite flow issues

community/community/doctype/community_member/community_member.py, community/community/widgets/Avatar.html, community/lms/doctype/lms_batch/lms_batch.py, community/widgets.py, community/www/courses/course.html
Added a widget for Avatar
1. With Photo
2. Without Photo
=> feat: Widget avatar

community/community/doctype/community_member/community_member.py, community/community/widgets/Avatar.html, community/lms/doctype/invite_request/invite_request.py, community/lms/widgets/RequestInvite.html, community/www/courses/about/index.html, community/www/courses/course.html, community/www/courses/course.js
=> fix: username and email validations

.gitignore
=> fix: gitignore dist folder

community/public/css/style.css, community/public/css/style.less, community/public/css/vars.css
Fixes #95 
Linked PR https://github.com/fossunited/mon_school/pull/1
=> fix: removed primary color from app

community/lms/doctype/lms_batch_membership/lms_batch_membership.json, community/lms/doctype/lms_course/lms_course.py, community/lms/widgets/CourseTeaser.html
This allows the students to directly jump to the learning section of the batch.
Closes #101 and #102.
=> Added "Resume Course" button to the course teaser

community/lms/api.py, community/lms/doctype/lms_batch/lms_batch.py, community/lms/doctype/lms_batch_membership/lms_batch_membership.json, community/lms/doctype/lms_batch_membership/lms_batch_membership.py, community/lms/doctype/lms_batch_membership/test_lms_batch_membership.py, community/lms/doctype/lms_course/lms_course.py, community/www/batch/learn.html, community/www/batch/learn.py, community/www/batch/utils.py
The current lesson is maintained in the LMS Batch Membership and that is updated everytime a lesson page is visited.
Closes #103.
=> Redirect the learn page to the current lesson of the user

community/hackathon/doctype/community_project_member/community_project_member.py
error with NameError: name 'frappe' is not defined
=> frappe wasn't imported

community/lms/doctype/exercise/exercise.py
Removed the image generation when exercise is saved. The library used
for exercises has changed and generating the image doesn't work any
more.
=> fix: fixed error on saving exercises

community/lms/doctype/lms_batch_membership/lms_batch_membership.py, community/lms/doctype/lms_course/lms_course.py, community/lms/widgets/BatchTabs.html, community/www/batch/join.html, community/www/batch/utils.py, community/www/courses/course.js
Passing member for getting the current batch and updating current membership
=> fix: minor issues

community/hooks.py, community/lms/doctype/lms_batch/lms_batch.json, community/lms/web_form/add_a_new_batch/add_a_new_batch.json, community/lms/widgets/ChapterTeaser.html, community/www/courses/course.html
1. Add a new batch form url and field changes.
2. Progress UI fix
3. Title in batch will be non unique
=> fix: web form, progress ui, title non unique

community/lms/api.py, community/lms/doctype/lesson/lesson.py, community/lms/doctype/lms_batch/lms_batch.py, community/lms/doctype/lms_batch_membership/lms_batch_membership.json, community/lms/doctype/lms_batch_membership/lms_batch_membership.py, community/lms/doctype/lms_course/lms_course.json, community/lms/doctype/lms_course/lms_course.py, community/lms/doctype/lms_course/test_lms_course.py, community/lms/widgets/BatchTabs.html, community/lms/widgets/ChapterTeaser.html, community/lms/widgets/RenderBatch.html, community/public/css/style.css, community/www/batch/discuss.html, community/www/batch/discuss.py, community/www/batch/home.html, community/www/batch/home.py, community/www/batch/join.html, community/www/batch/learn.html, community/www/batch/learn.js, community/www/batch/learn.py, community/www/batch/members.html, community/www/batch/members.py, community/www/batch/progress.html, community/www/batch/progress.py, community/www/batch/utils.py, community/www/courses/course.html, community/www/courses/course.js, community/www/courses/course.py
=> feat: learning modes and batch switching

community/lms/doctype/lms_batch_membership/lms_batch_membership.py, community/lms/md.py, community/www/courses/course.py
Changes:
* feat: allow a student to be mentor of another batch
* fix: error in find_macros when the input is empty
* fix: error in linking lessons on course page
=> Various fixes from mon.school

community/www/batch/learn.py
1. Fixed next and previous URL condition on learn page
2. Fixed class name for PageExtension
=> fix: learn page

community/hooks.py, community/lms/doctype/exercise_submission/exercise_submission.json, community/plugins.py, community/templates/livecode/extension_footer.html, community/templates/livecode/extension_header.html, community/www/macros/livecode.html
=> fix: enabled livecode on community

community/lms/doctype/lesson/lesson.js, community/lms/doctype/lesson/lesson.json, community/lms/workspace/lms/lms.json
=> feat: lms workspace

community/www/batch/learn.html, community/www/batch/learn.py
Tracking of livecode execution is made possible by making the page
context with course, batch and lesson available in js.
Added a global page_context variable in js and the data for that gets
initialzied in the learn.py.
=> feat: make it possible to enable tracking for livecode execution

community/lms/doctype/lms_batch/lms_batch.py
We had to reshuffle students across batches as exams have starred  for many students in Kerala. Added a utility to switch batch, which can be called from the console.
=> feat: added a utililty to switch a student from one batch to another

community/www/profiles/profile.py
Profile page was importing Sketch which was removed recently, even
though it was not using that. Removed it to fix the issue.
=> fix: error on profile page

community/lms/doctype/invite_request/invite_request.py, community/templates/emails/lms_invite_request_approved.html
Currently updated keeping Mon.School in mind.
=> fix: fixed the email message sent out on signup

community/lms/doctype/invite_request/invite_request.py, community/templates/emails/lms_invite_request_approved.html
- fixed "Hello None" in invite email
- send email immediately
=> Fix invite email

community/www/courses/index.py
=> fix: only show the published courses on All Courses page

community/lms/doctype/chapter/chapter.json, community/lms/doctype/lms_course/lms_course.json, community/lms/doctype/lms_quiz/lms_quiz.json, community/lms/widgets/ChapterTeaser.html, community/lms/widgets/CourseCard.html, community/public/css/style.css, community/www/profiles/profile.html
=> fix: upcoming course and doctype cleanup

community/patches/v0_0/chapter_lesson_index_table.py
1. Reload Chapters and Lessons doctype to avoid patch failure.
=> fix: chapter lesson patch

community/hooks.py, community/lms/widgets/CourseCard.html, community/lms/widgets/Reviews.html, community/public/css/style.css, community/www/batch/learn.html, community/www/batch/learn.py, community/www/courses/course.html, community/www/courses/course.py, community/www/courses/index.html, community/www/courses/index.py
1. Default image for course cards
2. Resizing headers in lesson content
3. Write a review button visibility
4. Basic meta data on pages
=> fix: default image, meta, reviews, lesson headers

community/lms/doctype/lms_course/lms_course.py, community/lms/widgets/ChapterTeaser.html, community/public/css/style.css, community/www/batch/learn.js, community/www/batch/learn.py
=> fix: quiz, course outline, and lesson indexing

community/lms/doctype/lms_course/lms_course.py, community/lms/doctype/lms_course_interest/lms_course_interest.js, community/lms/doctype/lms_course_interest/lms_course_interest.json, community/lms/doctype/lms_course_interest/lms_course_interest.py, community/lms/doctype/lms_course_interest/test_lms_course_interest.py, community/lms/widgets/CourseCard.html, community/public/css/style.css, community/templates/emails/lms_course_interest.html, community/www/courses/course.html, community/www/courses/course.js, community/www/courses/course.py
1. For courses that are published but are marked as upcoming, the course home page will have a button called notify me when available.
2. On click of this button, the user's interest will be noted in a new doctype called LMS Course Interest.
3. Later when the course changed and Is Upcoming is unchecked then on save all users that had shown interest in this course will receive an email informing them of the course availability.
=> feat: notify me

community/overrides/test_user.py, community/overrides/user.py
1. Keeping only underscore and not hyphen as Frappe sets the default username with user score after signup.
2. Added validation message if the username exists if the user is not new.
3. Replaced complex code with simpler code.
Closes #166
=> fix: username issues

community/event_management/doctype/talk/talk.json, community/event_management/web_template/talk_section/talk_section.html, community/hooks.py
1. Talk card will now display the date and time of the talk.
2. Card image is now conditional.
3. If the user adds a preview image that would be displayed on the card.
4. If a preview image is not present but a video URL is added, then a thumbnail of the video would be displayed.
5. If Video URL is also missing then a grey placeholder will be displayed.
=> fix: talk card schedule

community/event_management/doctype/talk/talk.json, community/event_management/web_form/attendee_registration/attendee_registration.js, community/event_management/web_form/attendee_registration/attendee_registration.json, community/event_management/web_form/purpose_a_talk/purpose_a_talk.js, community/event_management/web_form/speaker_registration/speaker_registration.js
correct route of attendee registration
=> fix: attendee-route

community/event_management/doctype/speaker/speaker.js, community/event_management/doctype/talk/talk.py, community/event_management/web_form/attendee_registration/attendee_registration.json, community/event_management/web_form/exhibitor_registration/exhibitor_registration.js, community/event_management/web_form/purpose_a_talk/purpose_a_talk.json
1. Speaker doctype user filter
2. Talk doctype speaker not saving on the first attempt issue
3. Talk web form preview image field added
=> fix: web form issues

community/public/css/style.css, community/templates/certificate.html
=> fix: certificate ui

community/public/css/style.css, community/templates/certificate.html
=> fix: certificate-redesign

community/overrides/user.py
Change unedrscore to underscore
=> fix: spell check in Validation Message

community/lms/widgets/Reviews.html, community/public/css/style.css, community/templates/quiz.html, community/www/batch/learn.js
1. Made label of quiz clickable
https://user-images.githubusercontent.com/31363128/133613102-2f393db9-e2b9-431f-8861-eb96370ca5a4.mov
2. Change message when there is no review
3. Changed heading of review modal
4. Made space between each chapter consistent in course outline
=> fix: issues

community/overrides/user.py, community/page_renderers.py, community/www/profiles/profile.py
**Issue**
1. Username was not accepting accented characters.
2. This was causing an issue during signup
=> fix: Username validation

community/patches.txt, community/patches/v0_0/rename_chapters_and_lessons_doctype.py
1. Patch to move data to Chapter Reference and Lesson Reference doctype.
=> fix: Patch for chapters and lessons

community/lms/doctype/lms_course/lms_course.py, community/lms/report/course_progress_summary/course_progress_summary.js, community/lms/report/course_progress_summary/course_progress_summary.json, community/lms/report/course_progress_summary/course_progress_summary.py
1. Course Progress Summary is a report that summarizes the progress of members who have enrolled for a particular course.
2. The chart represents the percent of students who have completed a certain percentage of the course.
=> feat: course progress summary

community/lms/widgets/CourseCard.html
=> fix: clickable course cards from profile page

.github/workflows/ci.yml, community/lms/web_template/courses_enrolled/courses_enrolled.html, community/lms/web_template/courses_enrolled/courses_enrolled.json, community/lms/web_template/courses_mentored/courses_mentored.html, community/lms/web_template/courses_mentored/courses_mentored.json, community/lms/widgets/CourseCard.html, community/overrides/user.py, community/public/css/style.css, community/www/profiles/profile.html
1. Courses Enrolled and Courses mentored
2. When no enrolled courses
=> feat: dashboard web templates

school/public/css/style.css, school/templates/search_course/search_course.html, school/templates/search_course/search_course.js
=> feat: search empty state

school/lms/doctype/lms_settings/lms_settings.json, school/public/css/style.css, school/templates/search_course/search_course.html
**Search Settings:**
1. Search Settings added to LMS Settings.
2. Users can now enable or disable search from the settings.
3. They can also add a placeholder of their choice.
https://github.com/frappe/school/issues/266
=> fix: search settings

school/community/web_template/multiple_testimonials/multiple_testimonials.html, school/public/css/style.css
**Fixed height and shadow for testimonial cards:**
https://user-images.githubusercontent.com/31363128/143991586-d47059e4-f42b-49c2-94ff-a8f060a3cd81.mov
=> fix: Testimonial Cards height and shadows

school/hooks.py, school/lms/doctype/course_lesson/course_lesson.js, school/lms/doctype/course_lesson/course_lesson.py, school/lms/doctype/lesson_assignment/lesson_assignment.js, school/lms/doctype/lesson_assignment/lesson_assignment.json, school/lms/doctype/lesson_assignment/lesson_assignment.py, school/lms/doctype/lesson_assignment/test_lesson_assignment.py, school/plugins.py, school/public/css/style.css, school/templates/assignment.html, school/www/batch/learn.js, school/www/profiles/profile.html
1. Lessons now have an Assignment component where users can upload their assignment files.
2. Syntax to add the same is {{ Assignment("id-file_type") }}
3. Help article below lesson highlights the syntax
4. The component would look like this on the lesson before any file is uploaded.
5. After the user uploads a file.
6. Documents uploaded by the user gets saved in a new doctype called Lesson Assignment
7. When an Assignment is added to a lesson, a folder with the Lesson and Course name gets created. All the files that the user uploads for this Assignment get saved in the respective lesson folder.
=> feat: lesson assignment

school/lms/widgets/MemberCard.html, school/overrides/user.py, school/public/css/style.css, school/www/cohorts/subgroup.html, school/www/community/index.html, school/www/courses/course.html
1. Improved the user cards on the community page
=> fix: community cards

school/overrides/user.py
**Issue:**
Wrong country is getting set through ip-api.
**Fix:** 
Passing IP as a parameter to get the country.
=> fix: ip issue

school/lms/widgets/Reviews.html, school/public/css/style.css, school/public/icons/comment.svg
**Reviews Empty State Redesign**
=> style: Reviews Empty State Redesign

school/lms/widgets/CourseOutline.html, school/public/css/style.css, school/templates/quiz.html, school/www/batch/learn.py, school/www/courses/course.html, school/www/courses/course.js
1. Fixed Course Content spacing issues.
2. Made overlay fixed with respect to the top section of course home page. 
https://user-images.githubusercontent.com/31363128/155072003-57263b4c-980f-457e-b831-6f9fda017747.mov
3. Removed the Course Creators section from the course home page.
=> fix: translations and sidebar

school/lms/widgets/MemberCard.html, school/overrides/user.py, school/public/css/style.css, school/www/community/index.html, school/www/community/index.py
=> feat: community page redesign

school/community/web_template/multiple_testimonials/multiple_testimonials.html, school/public/css/style.css, school/www/profiles/profile.html
1. Removed unused CSS
2. Testimonials redesign
=> fix: css cleanup and testimonials redesign

.github/workflows/semantic.yml
Check for semantic pull requests before merge
=> chore: semantic pull request check

lms/lms/doctype/lms_quiz/lms_quiz.json, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/plugins.py, lms/public/css/style.css, lms/templates/quiz.html, lms/www/batch/learn.js
1. Quiz can now have a timer per question.
https://user-images.githubusercontent.com/31363128/168962967-b432892e-e7db-4a83-b69e-842c1fee0a6a.mov
2. Maximum number of Attempts can also be set for a quiz after which the user won't be able to attempt it.
=> feat: timer in quiz

lms/hooks.py, lms/lms/md.py, lms/lms/web_form/chapter/chapter.js, lms/lms/web_form/lesson/lesson.js, lms/lms/web_form/profile/profile.json, lms/lms/widgets/CourseOutline.html, lms/public/css/style.css, lms/public/js/common_functions.js, lms/templates/quiz.html, lms/www/batch/learn.html, lms/www/courses/course.js, lms/www/jobs/job.js
1. Replaced notification dialogs with alerts
2. Made work experience non-mandatory from profile
3. New look for course page
=> fix: replaced some dialogs with alerts

lms/public/css/style.css, lms/templates/quiz.html, lms/www/batch/learn.js
=> fix: quiz ui

lms/lms/web_template/multiple_testimonials/multiple_testimonials.html
=> fix: testimonials new design

lms/lms/doctype/lms_quiz_submission/lms_quiz_submission.json, lms/lms/workspace/lms/lms.json, lms/patches.txt, lms/patches/v0_0/quiz_submission_member.py
LMS Quiz Submission will now have a member field.
=> refactor: member field in lms quiz submission

lms/public/css/style.css, lms/www/jobs/index.html, lms/www/jobs/job.html
**Job List:**
**Job Details:**
=> fix: job board redesign

lms/lms/doctype/lms_certificate/lms_certificate.py, lms/public/css/style.css, lms/templates/certificate.html, lms/www/courses/certificate.html, lms/www/courses/certificate.js
1. Certificate can now be exported as PNG
2. Replaced border image with just border because border-image is not supported while export.
=> feat: export certificate

lms/hooks.py, lms/lms/doctype/lms_course/lms_course.py, lms/lms/utils.py, lms/lms/widgets/CourseCard.html, lms/lms/widgets/CourseOutline.html, lms/overrides/user.py, lms/patches.txt, lms/patches/v0_0/create_course_moderator_role.py, lms/public/css/style.css, lms/templates/courses_under_review.html, lms/www/batch/learn.html, lms/www/batch/learn.js, lms/www/batch/learn.py, lms/www/batch/quiz.html, lms/www/courses/course.html, lms/www/courses/course.js, lms/www/courses/course.py, lms/www/dashboard/index.html, lms/www/dashboard/index.py, lms/www/profiles/profile.html, lms/www/profiles/profile.js, lms/www/profiles/profile.py
1. LMS now has a new Role called Course Moderator.
2. Course Moderators can review the courses that are Under Review and publish them on the website.
3. Course Moderators can also grant Course Instructor and Course Moderator roles to other users.
4. They can also Edit any course.
=> feat: course moderator

lms/subscription_utils.py
Subscription add on details for Frappe LMS Saas
=> feat: subscription add ons

lms/hooks.py, lms/lms/doctype/lms_batch_membership/lms_batch_membership.json, lms/lms/utils.py, lms/lms/widgets/Reviews.html, lms/public/css/style.css, lms/public/js/common_functions.js, lms/templates/search_course/search_course.html, lms/www/courses/course.html, lms/www/courses/course.js, lms/www/courses/course.py
1. Fixed #394 
2. Position of buttons in the reviews section
3. Member Name will appear as the title in the list view of LMS Batch Membership
4. Changed toast message for when a user enrolls and submits a review.
5. The search bar on the course list page will have a default placeholder "Search".
=> fix: misc UX

lms/lms/doctype/lms_quiz_submission/lms_quiz_submission.json, lms/public/css/style.css, lms/templates/quiz.html, lms/www/batch/learn.html, lms/www/batch/learn.js
1. Fixed #398 
2. Better UI for information messages
3. Member Name will be the title for LMS Quiz Submission doctype
=> fix: quiz submission and other misc changes

lms/lms/widgets/NoPreviewModal.html, lms/lms/widgets/Reviews.html, lms/public/css/style.css, lms/www/courses/course.html, lms/www/jobs/job.html
=> fix: better modal UI

lms/lms/widgets/CourseOutline.html, lms/lms/widgets/NoPreviewModal.html, lms/www/courses/index.py
=> fix: don't show start learning from course page if self learning is disabled

lms/lms/doctype/cohort/cohort.json, lms/lms/doctype/lms_course/lms_course.py, lms/www/cohorts/cohort.html, lms/www/cohorts/index.py, lms/www/cohorts/subgroup.html, lms/www/courses/course.html
1. Fixed https://github.com/frappe/lms/issues/403#issuecomment-1277211703
2. Made slug field mandatory in cohorts.
3. Translations
4. Other misc UI
=> fix: cohort issue

lms/lms/doctype/lms_course/lms_course.py, lms/www/cohorts/cohort.html, lms/www/cohorts/index.html, lms/www/courses/course.html
**Issue:**
The cohorts page was not working.
**Fix:**
A function from the cohorts class was being called from the cohort object.
=> fix: cohorts

lms/lms/doctype/course_lesson/course_lesson.json, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/doctype/lesson_assignment/lesson_assignment.json, lms/lms/doctype/lesson_assignment/lesson_assignment.py, lms/lms/doctype/lms_course/lms_course.py, lms/lms/utils.py, lms/plugins.py, lms/public/css/style.css, lms/templates/assignment.html, lms/www/batch/learn.html, lms/www/batch/learn.js
1. Course Lesson doctype now has input fields for assignments from Desk and Portal.
---
**Desk:**
---
**Portal:**
---
2. The UI has also been improved.
---
**Before Submit:**
---
**After Submit:**
---
3. Assignments will not be stored in lesson-specific folders anymore.
=> refactor: assignments

lms/lms/doctype/lms_course_progress/lms_course_progress.json, lms/patches.txt, lms/patches/v0_0/set_member_in_progress.py, lms/public/css/style.css, lms/templates/statistics.html, lms/templates/stats.html, lms/www/courses/index.html
#420 
Courses Completed and Lessons Completed Stats will be shown in the Statistics section.
=> feat: course and lesson completion count

lms/lms/doctype/skills/skills.json, lms/lms/doctype/user_skill/test_user_skill.py, lms/lms/doctype/user_skill/user_skill.js, lms/lms/doctype/user_skill/user_skill.json, lms/lms/doctype/user_skill/user_skill.py, lms/patches.txt, lms/patches/v0_0/skill_to_user_skill.py
#437 
Renamed Skill doctype to User Skill
=> fix: renamed skill doctype to user skill

lms/hooks.py, lms/install.py, lms/lms/doctype/lms_settings/lms_settings.json, lms/lms/doctype/lms_settings/lms_settings.py, lms/patches.txt, lms/patches/v0_0/change_course_creation_settings.py, lms/patches/v0_0/change_role_names.py, lms/patches/v0_0/skill_to_user_skill.py
=> feat: LMS pages to navbar settings

lms/hooks.py, lms/install.py, lms/lms/doctype/lms_settings/lms_settings.json, lms/lms/doctype/lms_settings/lms_settings.py, lms/lms/md.py, lms/patches.txt
Reverting #446 
Those who don't want LMS Pages in the Navbar can simply remove the links from Website Settings Doctype.
=> revert: navbar settings

README.md
Documentation wrong path solve.
=> fix: doc url

lms/www/courses/index.html, lms/www/courses/index.py
=> feat: course count in list view

lms/job/doctype/job_opportunity/job_opportunity.js, lms/lms/doctype/lms_course/lms_course.js
Job Opportunity doctype will now have a **See on Website** link.
=> fix: see on website link in job opportunity

lms/lms/doctype/lesson_assignment/lesson_assignment.py, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/public/css/style.css, lms/www/batch/quiz.js
1. From the portal, if a quiz question was being created with multiple correct options, it wasn't getting saved that way.
2. Grading Assignment was given permission issue.
3. A weird tooltip was appearing beneath textbox for course description and lesson.
=> fix: quiz and assignment submission

lms/hooks.py, lms/install.py
=> fix: delete roles after uninstall

lms/lms/doctype/lesson_assignment/lesson_assignment.json, lms/lms/notification/assignment_submission_notification/assignment_submission_notification.json, lms/lms/notification/assignment_submission_notification/assignment_submission_notification.md, lms/lms/notification/assignment_submission_notification/assignment_submission_notification.py, lms/patches.txt, lms/patches/v0_0/add_evaluator_to_assignment.py
Fixes #492
A notification will be triggered to the Evaluator on assignment submission.
=> feat: notification on assignment submission

.gitignore, lms/lms/doctype/lms_course/lms_course.py, lms/lms/widgets/CourseOutline.html, lms/public/css/style.css, lms/public/js/common_functions.js
You can now move chapters and lessons from the LMS Portal.
https://user-images.githubusercontent.com/31363128/229103539-65002855-f559-42ec-81cf-73c522b22872.mov
=> feat: move chapters and lessons

.github/helper/install.sh, .github/helper/install_dependencies.sh, .github/helper/site_config.json, .github/workflows/ci.yml, .github/workflows/ui-tests.yml, .gitignore, cypress.config.js, cypress/e2e/course_creation.cy.js, cypress/fixtures/example.json, cypress/support/commands.js, cypress/support/e2e.js, lms/lms/doctype/lms_course/lms_course.json, package.json
UI test for the Course Creation Workflow
=> test: Course Creation UI

lms/lms/doctype/course_lesson/course_lesson.json, lms/lms/doctype/lms_course/lms_course.json, lms/patches.txt, lms/patches/v0_0/amend_course_and_lesson_editor_fields.py
Reverts:  https://github.com/frappe/lms/pull/497
=> revert: text editor for lesson and course

lms/lms/doctype/lms_class/lms_class.json, lms/lms/doctype/lms_class/lms_class.py, lms/public/js/common_functions.js, lms/www/classes/class.py
- Class will now have a seat count, start time, and end time field. All these fields are optional.
- If the number of students added to a class is more than the seat count a validation will trigger a message and prevent any more students from being added.
=> feat: Class seat count, start time and end time

lms/lms/doctype/lms_certificate/lms_certificate.py
When a certificate gets created, it will get shared with the member. This is done to give permission to members to download their certificates.
=> fix: share certificate with member on creation

lms/lms/doctype/course_chapter/course_chapter.py, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/doctype/lms_course/lms_course.py, lms/public/js/website.bundle.js, lms/www/batch/edit.js, lms/www/courses/create.js, lms/www/courses/outline.js
LMS will now track the Course Creation journey for analytics. The following- [x]  landed on the course creation form
- When a user lands on the course creation page
- When a user creates a course
- When a user lands on the course outline page
- When a user creates a chapter
- When a user lands on the lesson creation page
- When a user creates a lesson.
=> feat: analytics for course creation journey

lms/public/css/style.css
Changed the Primary Color back to Frappe Blue from Black
=> fix: change primary color back to frappe blue

lms/lms/widgets/CourseOutline.html, lms/public/css/style.css, lms/templates/lms_base.html, lms/www/batch/edit.html, lms/www/batch/learn.html, lms/www/courses/course.html, lms/www/courses/course.py, lms/www/courses/create.html, lms/www/jobs/job.py
1. Fixed the link preview for course details
2. Fixed the indentation of the course outline
3. Renamed Preview buttons to Back to ... labels
4. Added meta for Job Details
=> fix: course details link preview

lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.json, lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.py, lms/www/batch/learn.js
Assignments in lessons stopped working after #520 
Fixes #525
=> fix: assignment submission in lesson

lms/www/courses/create.html, lms/www/courses/create.js, lms/www/courses/outline.js
1. Better description for fields.
2. Tags creation by pressing comma (,)
3. Immediately close the chapter modal
=> fix: misc issues

lms/lms/doctype/lms_quiz_question/lms_quiz_question.json, lms/www/batch/quiz.html, lms/www/batch/quiz.js
Quiz options will be Small Text field now. Instructors can add more text to the options field.
=> feat: quiz option as small text

lms/install.py, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/patches/create_mentor_request_email_templates.py, lms/public/css/style.css, lms/templates/quiz.html, lms/www/batch/learn.js, lms/www/batch/quiz.html, lms/www/batch/quiz.js, lms/www/batch/quiz.py, lms/www/batch/quiz_list.py, lms/www/courses/outline.js
1. The quiz form becomes very long when users have more questions. Since all the fields were directly visible on the form, it needed a lot of scrolling. So now the questions will not be directly displayed on the form. Instead, there will be a list of questions. Users can click on a question to edit it.
2. The question field on the quiz form is now a text editor. So users can have more elaborate questions. They can also have images and lists in the question.
2. The quiz UI on the lesson page was kind of messy and everything seemed very jumbled. Now the quiz will be displayed in a box that gives a clear indication that it's a quiz and maintains a clean separation from other components of the page.
https://github.com/frappe/lms/assets/31363128/eb947e36-04a7-4dee-a684-79f838166029
=> fix: quiz enhancements

lms/lms/doctype/lms_category/lms_category.js, lms/lms/doctype/lms_category/lms_category.json, lms/lms/doctype/lms_category/lms_category.py, lms/lms/doctype/lms_category/test_lms_category.py, lms/lms/doctype/lms_class/lms_class.json, lms/lms/doctype/lms_class/lms_class.py, lms/public/css/style.css, lms/public/js/common_functions.js, lms/www/classes/class.html, lms/www/classes/class.py, lms/www/classes/index.html
You can now add a Medium and Category to your class.
=> feat: class medium and category

lms/hooks.py, lms/lms/doctype/lms_quiz/lms_quiz.json, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/overrides/user.py, lms/plugins.py, lms/public/css/style.css, lms/public/js/common_functions.js, lms/templates/quiz/quiz.html, lms/templates/quiz/quiz.js, lms/www/assignment_submission/assignment_submission.html, lms/www/batch/learn.html, lms/www/batch/learn.js, lms/www/batch/quiz.html, lms/www/batch/quiz.js, lms/www/batch/quiz.py, lms/www/classes/class.html, lms/www/classes/class.py, lms/www/classes/progress.html, lms/www/quiz_submission/quiz_submission.html, lms/www/quiz_submission/quiz_submission.py, lms/www/utils.py
- Moderators can now add quizzes to class.
- They can add and remove quizzes from the dialog that opens on click of Manage Assessments.
- Students can visit the quiz submission page from there when they open their progress page.
- From there they can attempt the quiz.
- With each attempt, they see the score from all previous attempts
- When a student has attempted the quiz, the moderator can verify the score from the student's progress page.
- Moderators can now set Max Attempts for a quiz from the LMS Portal.
- Once the number of attempts exceeds the max attempt, the student will no longer be able to attempt the quiz again.
https://github.com/frappe/lms/assets/31363128/244e6106-cbc6-4030-ab28-392fec01f2cc
=> feat: quiz in classes

.github/workflows/ci.yml, .github/workflows/ui-tests.yml, lms/lms/doctype/lms_assignment/lms_assignment.json, lms/lms/doctype/lms_class/lms_class.json, lms/lms/doctype/lms_class/lms_class.py, lms/lms/doctype/lms_quiz/lms_quiz.json, lms/lms/utils.py, lms/lms/widgets/CourseCard.html, lms/patches.txt, lms/public/css/style.css, lms/public/js/common_functions.js, lms/www/classes/class.html, lms/www/classes/class.js, lms/www/classes/class.py, lms/www/classes/index.html, lms/www/classes/index.py, lms/www/classes/progress.html, lms/www/courses/index.py, lms/www/people/index.html
https://github.com/frappe/lms/assets/31363128/05172816-796a-4b97-9545-7a5177b915a1
=> fix: class improvements

lms/public/css/style.css, lms/www/classes/class.js, lms/www/classes/progress.html
1. Fixed modal scroll issue
2. Added Quiz and Assignment creation button in the Assessment modal
3. Increased the progress page width.
=> fix: UX Improvements

docker/init.sh
=> fix: use node 18 for docker

lms/hooks.py, lms/install.py, lms/lms/doctype/class_course/class_course.json, lms/lms/doctype/course_evaluator/course_evaluator.json, lms/lms/doctype/course_evaluator/course_evaluator.py, lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.json, lms/lms/doctype/lms_certificate_request/lms_certificate_request.json, lms/lms/doctype/lms_certificate_request/lms_certificate_request.py, lms/lms/doctype/lms_class/lms_class.json, lms/lms/utils.py, lms/patches.txt, lms/patches/v1_0/create_class_evaluator_role.py, lms/public/js/common_functions.js, lms/www/classes/class.html, lms/www/classes/class.js, lms/www/classes/class.py, lms/www/classes/progress.html, lms/www/classes/progress.js, lms/www/classes/progress.py
1. LMS now has a Course Evaluator Role.
2. Evaluators will have access to LMS Class, Course Evaluator, and LMS Certificate Request doctype.
3. Students can schedule an evaluation from the class portal now.
4. On the class progress page, there will be a button called Schedule Evaluations.
5. Clicking on this button will open a dialog where students can select the course and date. Based on the date selected the slots get populated. The student can select a slot and then submit it.
6. Also the invite creation for an evaluation will not be immediate anymore.
7. A background job will run every hour and create invites for all previous requests.
https://github.com/frappe/lms/assets/31363128/f4b30435-ce8f-4f61-b171-4601c019d049
=> Class evaluator

lms/public/js/common_functions.js, lms/public/js/website.bundle.js, lms/templates/lms_base.html, lms/www/batch/edit.html, lms/www/classes/class.html, lms/www/classes/index.html
Telemetry was failing.
Router will now be set through the base template.
=> fix: telemetry

.github/workflows/ui-tests.yml, package.json
=> chore: remove dev dependencies

.github/helper/install_dependencies.sh
=> ci: remove mysql

lms/overrides/user.py
=> fix: dont validate user uploaded files

lms/public/css/style.css, lms/www/courses/index.html
=> fix: styling of course list menu

lms/lms/doctype/lms_quiz/lms_quiz.py
fixed https://github.com/frappe/lms/issues/565
**Before**
**After**
=> fix: Add question in quiz submission

lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.json, lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.py, lms/www/assignment_submission/assignment_submission.html, lms/www/assignment_submission/assignment_submission.js, lms/www/assignment_submission/assignment_submission.py
Students can now submit assignments as a URL.
https://github.com/frappe/lms/assets/31363128/4b01cc74-f6b3-4287-8d6a-8e271d2a8ec2
=> feat: Assignment as URL

lms/hooks.py, lms/lms/doctype/course_lesson/course_lesson.json, lms/lms/utils.py, lms/plugins.py, lms/public/css/style.css, lms/www/batch/edit.html, lms/www/batch/edit.js, lms/www/batch/learn.html
Instructors can now embed components in lessons. For now, the following components are supported for embed:
1. Google Slides
2. Vimeo Videos
3. Codepen
https://github.com/frappe/lms/assets/31363128/39542352-b0f2-4923-aea0-2f51dec81e8b
=> feat: embeds in lesson

lms/lms/utils.py, lms/www/batch/edit.js, lms/www/batch/learn.html
Changed Instructor Notes field from Text editor to Markdown Field
=> fix: instructor notes

lms/lms/doctype/lms_batch/lms_batch.js, lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/utils.py, lms/public/css/style.css, lms/public/js/common_functions.js, lms/www/batches/batch.py, lms/www/batches/batch_details.html, lms/www/batches/batch_details.py, lms/www/batches/index.py, lms/www/billing/billing.html, lms/www/billing/billing.js, lms/www/billing/billing.py, lms/www/courses/course.py, lms/www/courses/index.py
- This PR introduces a change in the billing flow. The price will be displayed to the users throughout the batch cycle based on their billing country. 
- Billing country will be identified by the address stored in the system with the user's email ID. 
- This way they will see prices based on the country from the start. 
- The price will be updated accordingly when a user changes the country from the billing form.
=> fix: billing flow

lms/lms/doctype/lms_certificate_evaluation/lms_certificate_evaluation.json, lms/www/billing/billing.html, lms/www/billing/billing.js, lms/www/billing/billing.py
=> fix: billing flow issues

cypress/e2e/course_creation.cy.js, lms/lms/doctype/course_lesson/course_lesson.json, lms/lms/utils.py, lms/public/css/style.css, lms/www/batch/edit.html, lms/www/batch/edit.js, lms/www/batch/learn.html, lms/www/batch/learn.py, lms/www/batches/batch_details.html
Editor JS is now being used for Instructor Notes too. So you can add all plugins in instructor notes as well.
https://github.com/frappe/lms/assets/31363128/0ffe2fe4-c8f3-4626-93b3-a052f991e009
=> feat: editor js for instructor notes

lms/lms/doctype/lms_batch/lms_batch.json, lms/www/batches/batch.html, lms/www/batches/batch.py
All components of the batch come from the core app, but if you want to customize a few things based on your use case you can do so now.
You can now add basic HTML and JavaScript code on the main batch page above the tabs using these fields in the LMS Batch DocType.
You can use the Custom HTML field to add the HTML components and add actions for the same in JavaScript using the Custom Script fields. They will be rendered this way.
You can now add more tabs to the batch page based on your use case. This can only be done with a custom app that works on top of the LMS App. You need to use a hook called lms_batch_tabs. This hook is an object with 3 properties.
1. header_html: This is an HTML file with the HTML for the tabs header. Make sure to follow the proper syntax of the tab header. You …
=> feat: batch customisations

lms/install.py, lms/job/doctype/job_opportunity/job_opportunity.json, lms/lms/api.py, lms/lms/doctype/cohort_join_request/cohort_join_request.json, lms/lms/doctype/course_chapter/course_chapter.json, lms/lms/doctype/course_lesson/course_lesson.json, lms/lms/doctype/function/function.json, lms/lms/doctype/industry/industry.json, lms/lms/doctype/lms_enrollment/lms_enrollment.json, lms/lms/doctype/user_skill/user_skill.json, lms/lms/test_utils.py, lms/lms/utils.py, lms/overrides/user.py, lms/patches.txt, lms/patches/v1_0/create_student_role.py
LMS now has a role for students called LMS Student. All new Website users will by default have this role.
=> feat: LMS Student Role

lms/hooks.py, lms/plugins.py, lms/www/batch/edit.js
PDF was rendered but there was no proper way of uploading PDF from the UI. You can now upload PDFs directly from the lesson creation form.
https://github.com/frappe/lms/assets/31363128/c6630354-170d-40c6-b10e-4d1e57546eeb
=> fix: pdf rendering in lessons

lms/lms/doctype/lms_batch/lms_batch.py, lms/public/css/style.css, lms/www/batches/batch.html, lms/www/batches/batch.js, lms/www/batches/batch_details.py
Moderators can now share an email with students of the batch from the main batch page.
https://github.com/frappe/lms/assets/31363128/abf63c35-7568-4d57-ae1c-ee709e1b84eb
=> feat: send email to batch students

.github/helper/install.sh, .github/workflows/ci.yml, lms/lms/doctype/lms_batch/lms_batch.js, lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_timetable_legend/lms_timetable_legend.js, lms/lms/doctype/lms_timetable_legend/lms_timetable_legend.json, lms/lms/doctype/lms_timetable_legend/lms_timetable_legend.py, lms/lms/doctype/lms_timetable_legend/test_lms_timetable_legend.py, lms/lms/doctype/lms_timetable_template/lms_timetable_template.js, lms/lms/doctype/lms_timetable_template/lms_timetable_template.json, lms/www/batches/batch.html, lms/www/batches/batch.js, lms/www/batches/batch.py
LMS Timetable Template doctype will now have a child table for legends. Here you can add a label and color for each activity in the timetable.
You can also not allow students to access activities with future dates by disabling this in LMS Batch.
=> feat: timetable customisations

lms/lms/doctype/lms_assignment/lms_assignment.py, lms/lms/doctype/lms_course/lms_course.py, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/lms/utils.py, lms/www/assignments/assignment.py, lms/www/batch/quiz.py, lms/www/batch/quiz_list.py, lms/www/courses/course.py, lms/www/courses/create.py, lms/www/courses/index.py, lms/www/courses/outline.py
1. Fixes course creation and edit permissions.
2. Fixes enrollment chart permissions.
=> fix: permissions

lms/lms/doctype/lms_payment/lms_payment.json, lms/lms/utils.py
=> feat: store batch/course in LMS Payment

lms/lms/doctype/lms_batch/lms_batch.py, lms/www/batches/batch.js
=> feat: add reply_to in email students dialog

lms/www/courses/certificate.html, lms/www/courses/certificate.py
1. Moderators will be allowed to download certificates
2. Certificate download will now pick the certificate template as the print format.
=> fix: certificate download template

lms/www/batches/index.py, lms/www/billing/billing.js, lms/www/billing/billing.py
1. Fixes billing multicurrency issue.
2. Archived and Enrolled batches will now be displayed in the descending order of start date.
3. If the billing country is India, then the billing state will be mandatory and there will be a validation to check the correctness of the state.
=> fix: misc batch issues

SECURITY.md
Created and enabled Security Policy
=> chore: created security policy

lms/lms/utils.py, lms/www/batch/learn.py
=> fix: 10th lesson access issue

lms/lms/doctype/lms_quiz/lms_quiz.json
Closes https://github.com/frappe/lms/issues/664
=> fix: mandatory total marks issue

cypress.config.js, lms/www/courses/create.py, pyproject.toml, requirements.txt
Added pyproject.toml for build
=> build: added pyproject.toml

lms/lms/doctype/lms_batch/lms_batch.js
=> fix(LMS Batch): add portal web link to form view

lms/templates/emails/batch_confirmation.html
Changed the copy of the enrolment email
=> fix: copy of enrolment email

lms/lms/doctype/lms_batch/lms_batch.py, lms/www/batches/batch.py
Moderators were unable to save meta image from the LMS Portal.
=> fix: batch meta image saving

lms/lms/doctype/lms_certificate_request/lms_certificate_request.py
When 2 users try scheduling evaluation for the same course at the same time and end up selecting the same slot, evaluation gets scheduled for both for the same slot as there is no validation in the backend for the same.
Now a validation in backend will check if the slot is booked then a message will be shown to the other user that the slot is unavailable.
=> fix: evaluation dates validation

lms/www/batches/batch_details.html
If a student opened a batch details page with the URL, the details were visible along with the registration button.
=> fix: batch registration button conditions

frontend/index.html, lms/hooks.py, lms/public/frontend/index.html
Web Templates were breaking
Added web_include_css back in hooks.py
=> fix: web templates

frontend/src/components/CourseCardOverlay.vue, frontend/src/components/Discussions.vue, frontend/src/components/MobileLayout.vue, frontend/src/pages/Batches.vue, frontend/src/pages/CreateCourse.vue, frontend/src/pages/CreateLesson.vue, lms/hooks.py, lms/www/certificate.py
1. Fixed mobile layout for all the main pages
2. Fixed old certificate link redirection
=> fix: mobile layout and certification link

frontend/src/components/Assessments.vue, frontend/src/components/UserDropdown.vue, frontend/src/pages/AssignmentSubmission.vue, frontend/src/pages/CreateCourse.vue, frontend/src/router.js, frontend/src/stores/session.js, lms/lms/doctype/lms_assignment/lms_assignment.json, lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.json, lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.py
1. Added assignments for batches. It works the same as before.
https://github.com/frappe/lms/assets/31363128/b996d552-6217-43eb-845f-09bcf81178e9
=> feat: assignments in batches

frontend/src/components/CourseCard.vue, frontend/src/components/LessonContent.vue, frontend/src/components/Quiz.vue, frontend/src/pages/CreateLesson.vue, lms/lms/utils.py
=> fix: lesson youtube video issue

frontend/src/components/BatchCard.vue, frontend/src/components/BatchOverlay.vue, frontend/src/components/Common/DateRange.vue, frontend/src/pages/Batch.vue, frontend/src/pages/BatchDetail.vue, frontend/src/utils/index.js
* Handle case when start date and end date are same
* DRY up code
=> fix: batch date range

frontend/src/pages/Billing.vue, frontend/src/pages/Courses.vue, frontend/src/pages/ProfileCertificates.vue, lms/job/doctype/lms_job_application/lms_job_application.py, lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_course/lms_course.json, lms/lms/utils.py, lms/patches.txt, lms/patches/v1_0/set_published_on.py, lms/templates/emails/job_application.html
1. A **New** tab on the course list page will show all the courses that get published within 3 months.
2. Fixed billing page redirection issue after login.
3. Added certificate PDF link from the profile page.
4. Fixed attachment in the job application email.
=> feat: new tab and other misc fixes

frontend/src/pages/CertifiedParticipants.vue, frontend/src/router.js, frontend/src/utils/index.js, lms/lms/api.py, lms/lms/doctype/lms_live_class/lms_live_class.py
All users having an LMS Certificate thats published will be listed on this page with a list of courses they are certified for.
=> feat: certified participants

frontend/src/components/CourseOutline.vue, frontend/src/components/LessonContent.vue, frontend/src/components/Modals/YouTubeExplanation.vue, frontend/src/pages/CreateCourse.vue, frontend/src/pages/CreateLesson.vue, frontend/src/pages/Lesson.vue, frontend/src/utils/index.js, frontend/src/utils/upload.js, frontend/yarn.lock
Fixed:
1. Issue of adding empty lines in the lesson.
2. Issue of downloading the video of the lesson by right-clicking.
3. Spacing for course outline.
=> fix: misc lesson issues

frontend/src/components/CourseOutline.vue, frontend/src/pages/CourseDetail.vue, frontend/src/pages/CreateCourse.vue, lms/lms/doctype/lms_certificate/lms_certificate.py, lms/lms/doctype/lms_course/lms_course.py, lms/lms/doctype/lms_course/test_lms_course.py, lms/www/lms.py
1. Fixed meta for course creation page.
2. Fixed list style for course description.
3. Fixed outline header style on course creation page.
=> fix: misc fixes

frontend/src/pages/CertifiedParticipants.vue, lms/lms/api.py
Got an slight ick while browsing through the cerificates page 😅, so made the page searchable.
https://github.com/frappe/lms/assets/61804369/cbfb3baa-323c-4a84-a8b1-fc874be59b4b
=> feat: CertifiedParticipants.vue page is now searchable

lms/patches/v1_0/rename_evaluator_role.py
for whatever reason this role already existing on one of the sites I tried migrating ...
=> fix: check if role exists before renaming

frontend/src/components/BatchCourses.vue, frontend/src/components/BatchStudents.vue, frontend/src/pages/Batch.vue, frontend/src/pages/CertifiedParticipants.vue, frontend/src/pages/ProfileCertificates.vue, lms/lms/api.py, lms/lms/utils.py, lms/www/lms.py
1. Certified Participants page mobile view.
2. Fixed job page meta
3. Fixed course deletion from batch
4. Fixed search bar position on the certified participant's page.
=> fix: certified participants page mobile layout

.github/workflows/linters.yml, frontend/src/components/BatchOverlay.vue, frontend/src/components/MobileLayout.vue, frontend/src/pages/BatchDetail.vue, frontend/src/pages/CreateLesson.vue, frontend/src/pages/Profile.vue, frontend/src/pages/ProfileAbout.vue, frontend/src/pages/ProfileCertificates.vue, frontend/src/pages/ProfileEvaluator.vue, frontend/src/pages/ProfileRoles.vue, frontend/src/pages/Statistics.vue, frontend/src/stores/session.js, lms/patches.txt, lms/patches/v2_0/fix_progress_percentage.py
1. Fixed profile page mobile view
2. Added Log In, Log Out, and Profile options on mobile navigation.
3. Fixed #809 
4. Fixed #796
5. Fixed #807
=> fix: mobile and lesson issues

frontend/src/components/BatchCourses.vue, frontend/src/pages/Batches.vue
=> fix: batch related issues

frontend/src/components/AppSidebar.vue, frontend/src/pages/JobDetail.vue, lms/hooks.py, lms/job/doctype/job_opportunity/job_opportunity.py, yarn.lock
1. The job details page will now show the number of people applying for this job.
2. Any job posting older than 3 months will be closed automatically by a scheduler.
3. Fixed #854
=> feat: job application count

frontend/src/components/BatchOverlay.vue
Registration button was visible in sold out batches.
=> fix: sold out batch issue

frontend/src/components/LiveClass.vue, frontend/src/pages/Batch.vue, frontend/src/pages/Lesson.vue, frontend/src/router.js, frontend/src/stores/user.js, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/utils.py
=> fix: perf issues

frontend/src/components/CourseCard.vue, frontend/src/components/ProgressBar.vue, frontend/src/pages/Lesson.vue
=> fix: clip progress bar width to 100%

frontend/src/components/BatchCard.vue, frontend/src/components/CourseCard.vue, frontend/src/pages/Batch.vue, frontend/src/pages/BatchDetail.vue, frontend/src/pages/CourseDetail.vue, frontend/src/pages/Lesson.vue
Fix #886 
Center aligned instructor info.
=> fix: batch ui

frontend/src/components/CourseReviews.vue, frontend/src/components/JobCard.vue, frontend/src/components/MobileLayout.vue, frontend/src/pages/CourseDetail.vue, frontend/src/pages/Jobs.vue
1. Icons in the navigation bar on mobile were not visible.
2. Jobs page UI for mobile.
3. #874
=> fix: minor UI issues

frontend/src/pages/CreateLesson.vue
=> fix: lesson editor menu position

frontend/src/components/CourseReviews.vue, frontend/src/pages/CertifiedParticipants.vue, frontend/src/pages/Courses.vue, lms/lms/utils.py
You can now search for courses from the list.
https://github.com/frappe/lms/assets/31363128/3fdbf7a2-6d71-45c9-80dc-6f369344c1b2
=> feat: search courses

.github/helper/update_pot_file.sh, .github/workflows/generate-pot-file.yml, crowdin.yml, lms/locale/es.po, lms/locale/main.pot
Allows translation of LMS strings directly in the UI.
Context: https://github.com/frappe/frappe/pull/25677
=> feat: translations via gettext

frontend/src/components/Quiz.vue
=> fix: instructions for user input questions

frontend/src/pages/Courses.vue, frontend/src/pages/ProfileAbout.vue, lms/lms/utils.py
Course page was not being cached properly
=> fix: course cache issue

frontend/src/components/CourseOutline.vue, frontend/src/pages/CreateCourse.vue, lms/lms/api.py
Moderators can now delete the lesson from the portal. Closes #891 
https://github.com/frappe/lms/assets/31363128/9dfb82be-1818-4d30-adfe-9fd1a5cb8ee2
=> feat: delete lessons

frontend/src/pages/Batches.vue, frontend/src/pages/Courses.vue, frontend/src/stores/session.js, frontend/src/stores/user.js, lms/lms/api.py, lms/lms/utils.py
#929 
Users can now Filter batches based on categories.
https://github.com/user-attachments/assets/f92f211a-4c64-4782-b521-5b68f45d2b01
=> feat: batch categories filter

lms/lms/doctype/lms_certificate_request/lms_certificate_request.py, lms/lms/notification/certificate_request_creation/certificate_request_creation.html, package.json, yarn.lock
1. Fixed the notification email for certification.
2. Fixed the duplication checking.
=> fix: eval request issues

frontend/src/components/BatchCard.vue, frontend/src/components/CourseCard.vue, frontend/src/pages/JobDetail.vue, lms/hooks.py
1. Course Cards
2. Batch Cards
3. Jobs
=> fix: spacing and widths

frontend/src/components/AppSidebar.vue, frontend/src/components/CourseOutline.vue, frontend/src/components/MobileLayout.vue, frontend/src/pages/Batches.vue, frontend/src/pages/CertifiedParticipants.vue, frontend/src/pages/Courses.vue, frontend/src/pages/Lesson.vue, frontend/src/pages/LessonForm.vue, frontend/src/pages/ProfileAbout.vue, frontend/src/router.js, frontend/src/stores/session.js, frontend/src/utils/index.js, lms/hooks.py
1. Lessons will now be auto saved when you are editing. Closes #950 
2. Hide sidebar items on mobile. Closes #939 
3. Fixed navbar for courses in mobile view
=> fix: lesson auto save

.github/workflows/make_release_pr.yml
Automated release PR on every Wednesday
=> ci: automated release PR

frontend/src/components/Modals/Settings.vue, frontend/src/components/SettingDetails.vue
=> fix: settings ui

frontend/src/components/CourseCardOverlay.vue, lms/lms/doctype/course_chapter/course_chapter.py, lms/lms/doctype/course_lesson/course_lesson.py, lms/lms/doctype/lms_course/lms_course.py, lms/www/lms.py
Learning will now capture the cycle of course progress. The following steps will be captured.
a. Enrolled in a course.
b. Completed 25% of the course.
c. Completed 50% of the course.
d. Completed 75% of the course.
e. Completed 100% of the course.
=> chore: analytics for course completion

lms/lms/doctype/lms_certificate_request/lms_certificate_request.py, lms/patches.txt, lms/patches/v2_0/delete_certificate_request_notification.py
1. Evaluator name was not getting saved in Certificate Request
=> fix: evaluator name issue

lms/lms/doctype/lms_settings/lms_settings.json, lms/plugins.py, lms/templates/signup-form.html
Fixed signup customisations condition.
=> fix: signup conditions

frontend/src/App.vue, frontend/src/components/LiveClass.vue, frontend/src/components/Modals/Settings.vue, frontend/src/stores/session.js, lms/lms/doctype/course_lesson/course_lesson.py
1. Initialise telemetry only if the user is logged in.
2. Fixed the telemetry capture during lesson progress.
3. Fixed the UI of Live Class listing
=> fix: misc UI fixes

cypress/e2e/course_creation.cy.js, frontend/src/components/AppSidebar.vue, frontend/src/components/MobileLayout.vue, frontend/src/components/Modals/Question.vue, frontend/src/components/Quiz.vue, frontend/src/components/SidebarLink.vue, frontend/src/pages/Batches.vue, frontend/src/pages/Billing.vue, frontend/src/pages/Courses.vue, frontend/src/pages/ProfileAbout.vue, frontend/src/pages/QuizForm.vue, frontend/src/pages/QuizPage.vue, frontend/src/pages/QuizSubmission.vue, frontend/src/pages/QuizSubmissionList.vue, frontend/src/pages/Quizzes.vue, frontend/src/router.js, lms/lms/doctype/lms_question/lms_question.json, lms/lms/doctype/lms_question/lms_question.py, lms/lms/doctype/lms_quiz/lms_quiz.py, lms/lms/doctype/lms_quiz_question/lms_quiz_question.json, lms/lms/doctype/lms_quiz_result/lms_quiz_result.json, lms/lms/doctype/lms_quiz_submission/lms_quiz_submission.json, lms/lms/doctype/lms_quiz_submission/lms_quiz_submission.py
1. Instructors can now make open-ended quizzes.
2. For this, instructors have to make sure all questions of such quizzes are open-ended.
3. Open-ended questions won't be graded immediately. 
4. After completing the quiz, students will see a message informing them that they will know the result once the instructor has graded it.
5. The instructor can check all the submissions of the quiz. Clicking on a submission takes them to the details page where they see the response of the student.
6. There they can grade the response of the student and the final percentage will be calculated.
https://github.com/user-attachments/assets/6c4dd566-ad12-4672-a84f-91f8d805f5b2
=> feat: open ended questions

frontend/src/pages/QuizForm.vue
=> fix: quiz columns

lms/lms/payments.py
Razorpay checkout was not working.
=> fix: create order for razorpay

frontend/src/pages/Lesson.vue, frontend/src/pages/QuizForm.vue, lms/lms/utils.py
1. Fixes #1051 
2. A button to open the quiz page from the quiz form.
=> fix: misc quiz issues

frontend/package.json, frontend/src/components/BrandSettings.vue, frontend/src/components/Controls/CodeEditor.vue, frontend/src/components/CourseCardOverlay.vue, frontend/src/components/Modals/Settings.vue, frontend/src/components/SettingDetails.vue, frontend/src/components/SettingFields.vue, frontend/src/pages/JobCreation.vue, frontend/src/utils/index.js, frontend/yarn.lock, lms/lms/api.py
1. Improved the code editor used in signup settings
2. Show proper error message if the image is missing from the Job Form
3. Evaluator slots were not being displayed on their profile page.
4. Changed the UI of brand images in Settings
5. When searching for a member, the email id search does not work.
6. Proper toast when a user enrolls for a course.
=> fix: misc ux issues

frontend/src/components/Assessments.vue, frontend/src/components/AudioBlock.vue, frontend/src/components/BatchOverlay.vue, frontend/src/components/BrandSettings.vue, frontend/src/components/CourseCardOverlay.vue, lms/lms/doctype/lms_assessment/lms_assessment.json, lms/lms/utils.py
Batch self enrollment was not working
=> fix: batch self enrollment

lms/lms/utils.py
Students were not getting enrolled in the batch after completing the payment.
=> fix: batch enrollment after payment completion

lms/lms/doctype/lms_quiz/lms_quiz.py
Removed the condition which was resetting show_answers in LMS Quiz
This will fix the issue #1097
=> fix: removed unnecessary condition which resets show_answers to False

lms/lms/api.py
=> fix: 500 error on get_branding api call

frontend/src/components/Modals/EditProfile.vue
=> feat: rich text editor in bio

frontend/src/components/Controls/Link.vue, frontend/src/components/Modals/AnnouncementModal.vue, frontend/src/components/Modals/BatchCourseModal.vue, frontend/src/components/Modals/ChapterModal.vue, frontend/src/components/Modals/LiveClassModal.vue, frontend/src/pages/Batch.vue, frontend/src/pages/BatchForm.vue, frontend/src/pages/LessonForm.vue
Maybe closes #899
- Add required attribute in batches form
- Make Tabs sticky in Batches
https://github.com/user-attachments/assets/622148b7-2809-422a-8990-bce449354e42
=> feat: add required attribute and make tab sticky in batches

frontend/src/components/Modals/ChapterModal.vue
Improved the UX of chapter modal for adding SCORM
=> fix: changed SCORM input from checkbox to switch with better description

lms/install.py, lms/lms/doctype/lms_course/lms_course.py, lms/patches.txt, lms/patches/v2_0/update_desk_access_for_lms_roles.py
1. LMS roles were being created with desk access enabled.
2. Because of this even students were able to access desk.
=> fix: desk access and course amount validation issue

frontend/src/components/Members.vue
Closes #1126 
- Before Fix
---
- After Fix
=> fix: show role for members

frontend/src/components/BatchStudents.vue, frontend/src/pages/QuizSubmissionList.vue
1. The Quiz Submission list now has a load more button that records from the next page.
2. Changed the order of columns on batch students table to show assessments before courses.
=> feat: load more in quiz submissions

frontend/src/pages/Quizzes.vue, frontend/src/utils/markdownParser.js
=> feat: load more in quiz list

.github/workflows/build.yml, frontend/src/utils/markdownParser.js
1. Fixes embed issue
2. Fixes markdown paste issue
3. Given write permission to docker image workflow
=> fix: markdown embed and paste issue

frontend/package.json, frontend/src/components/BatchStudents.vue, frontend/src/components/Modals/BatchStudentProgress.vue, frontend/src/components/ProgressBar.vue, frontend/src/pages/Batch.vue, frontend/yarn.lock, lms/lms/utils.py
Moderators and Evaluators will now see a dashboard on the batch page. The dashboard shows overall batch statistics and a graph that shows how many students have completed the courses and assessments. 
Below the graph is the student's list. Clicking on individual rows opens up the progress of that student.
=> feat: batch student progress modal

frontend/src/components/BatchStudents.vue, frontend/src/components/CourseCardOverlay.vue, frontend/src/pages/CourseDetail.vue, lms/lms/utils.py
1. Made batch dashboard graph horizontal.
2. Changed the colors of the graphs on the dashboard.
3. Display the rating on the course details page only if it is greater than 0.
=> fix: progress issue in batches

frontend/src/components/Quiz.vue, lms/lms/utils.py
=> fix: quiz api issue

frontend/src/utils/assignment.js, frontend/src/utils/quiz.js
- Assignment Form is popped up when New Quiz is tried to be added in Lesson Edit form
- Issue is arising due to missing prop passed in AssessmentPlugin Component
https://github.com/user-attachments/assets/2b9db481-4017-4c7f-b9d6-69bd793a6127
=> fix: fix issue where assignment form is popped up on add quiz button in Lesson Edit form

frontend/src/pages/Batches.vue
**Mobile:**
**IPad:**
**Laptop (Small):**
**Regular Screens:**
=> fix: batch list responsive cards

frontend/src/pages/Batches.vue, frontend/src/pages/CertifiedParticipants.vue, lms/lms/api.py
https://github.com/user-attachments/assets/d32c2a26-64c2-4576-8a68-8060fad76895
=> refactor: improved ui and performance for certified participants page

frontend/src/components/JobCard.vue, frontend/src/pages/Jobs.vue
=> fix: improved jobs page ui

frontend/src/components/ProgressBar.vue, frontend/src/components/Quiz.vue, frontend/src/pages/Jobs.vue, lms/lms/api.py
1. The Jobs page was not rendering for guest users.
2. Fixed the styling of the quiz timer.
=> fix: jobs page rendering issue for guest users

frontend/src/components/Assignment.vue, frontend/src/components/BatchStudents.vue, frontend/src/components/Modals/AnnouncementModal.vue, lms/lms/api.py, lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_batch_enrollment/lms_batch_enrollment.py
1. Announcement Modal now has a fixed editor. 
2. Instructors will now see a Certification count on their batch dashboard.
3. Linked LMS Certificate Evaluation and LMS Certificate to LMS Batch doctype.
4. During assignments, if students uploaded one file and later wanted to change another, the old file was still being maintained after saving. Fixed that.
=> fix: misc batch flow changes

frontend/src/components/BatchOverlay.vue, lms/lms/utils.py
After https://github.com/frappe/lms/pull/1309 even if students were enrolled to private batches, they were unable to access it. This PR fixes the issue.
=> fix: students should have access private batch if enrolled

frontend/src/components/Assignment.vue, frontend/src/pages/Batch.vue, lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.json
The comments field in Assignment Submission is now a Text Editor
=> feat: assignment comments is now text editor

frontend/src/pages/Batch.vue, lms/hooks.py, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_batch_enrollment/lms_batch_enrollment.py, lms/lms/doctype/lms_live_class/lms_live_class.py, lms/templates/emails/batch_start_reminder.html, lms/templates/emails/live_class_reminder.html
Students will now receive email reminders:
1. For their batch, a day before it starts.
2. Live Class reminder on the day of the class.
=> feat: batch start and live class reminder

cypress.config.js, cypress/e2e/course_creation.cy.js, frontend/src/components/Members.vue, frontend/src/pages/LessonForm.vue, frontend/src/utils/markdownParser.js
=> fix: link issue in lesson

frontend/package.json, frontend/src/components/Modals/BatchCourseModal.vue, frontend/src/components/Modals/ChapterModal.vue, frontend/src/components/Modals/DiscussionModal.vue, frontend/src/components/Modals/EditProfile.vue, frontend/src/components/Modals/EvaluationModal.vue, frontend/src/components/Modals/JobApplicationModal.vue, frontend/src/components/Modals/ReviewModal.vue, frontend/src/pages/Batch.vue
Now if the instructor goes somewhere from the dashboard or refreshes the page, they land back on the same tab they left from!
=> feat(batch): track active tab in URL/route

frontend/src/components/Controls/Autocomplete.vue, frontend/src/components/Modals/LiveClassModal.vue, frontend/src/pages/Batch.vue
Also did some misc fixes:
- **chore: remove unused imports**
- **fix: transform tabIndex query param to number**
=> feat: timezone autocomplete in live class & misc fixes

frontend/src/components/CourseCard.vue, frontend/src/pages/Courses.vue, frontend/tailwind.config.js, lms/lms/doctype/lms_course/lms_course.json, lms/lms/utils.py
https://github.com/user-attachments/assets/9b22acf6-0170-48e1-aef1-30a05c034379
=> refactor: course list fetching and filters

cypress/support/commands.js, frontend/src/pages/LessonForm.vue, frontend/src/utils/index.js, frontend/src/utils/markdownParser.js, frontend/yarn.lock, yarn.lock
=> fix: youtube embed issue

frontend/src/pages/Batches.vue, frontend/src/pages/Courses.vue, frontend/src/pages/Programs.vue
In portal Courses page text "All Courses" and in Program page program name and in Batchs page text "All Batchs" is not visible in dark theme need to change the text colour to tailwind css class "text-ink-gray-9"
=> change the text color according to the theme

frontend/src/pages/CourseDetail.vue, lms/lms/utils.py
Courses were not visible on the batch details page
=> fix: course tags issue when getting course details

frontend/src/components/AssignmentBlock.vue
=> fix: removed user info from assignment block

frontend/src/components/Controls/CodeEditor.vue, frontend/src/components/Modals/Settings.vue, frontend/src/components/SettingFields.vue, lms/lms/doctype/lms_settings/lms_settings.json, lms/lms/doctype/lms_settings/lms_settings.py, lms/templates/signup-form.html
=> feat: signups can now be enabled/disabled from portal settings

.github/workflows/linters.yml, .github/workflows/ui-tests.yml, commitlint.config.js, frontend/index.html, frontend/src/components/UserDropdown.vue, lms/www/lms.py
1. Show App Name from Website Settings as document title if present.
2. If a favicon is missing fall back to the app logo
3. Show course description and batch details in meta description
4. Fetch meta tags from Website Route Meta and use them with document information for Meta tags.
=> fix: seo improvements

frontend/src/components/JobCard.vue, frontend/src/pages/JobDetail.vue, frontend/src/pages/Jobs.vue, lms/lms/api.py
1. Improved the layout with three columns.
2. Added a Visit Website button that redirects to the company website.
=> fix: new ui for job list

.github/workflows/make_release_pr.yml, frontend/src/components/JobCard.vue, frontend/src/pages/CertifiedParticipants.vue, frontend/src/utils/index.js, lms/lms/api.py, lms/www/lms.py
=> fix: improved UI of certified participants page

frontend/src/components/AppSidebar.vue, frontend/src/components/UserDropdown.vue, lms/public/css/style.css
1. Moved "Powered by Learning" to the bottom of the sidebar.
2. Fixed #1445
=> fix: moved powered by learning to the bottom of sidebar

cypress/e2e/course_creation.cy.js, frontend/src/components/CourseCard.vue, frontend/src/pages/CourseDetail.vue, frontend/src/utils/index.js
=> fix: allow fullscreen on vimeo

frontend/src/components/UserDropdown.vue, frontend/src/pages/Courses.vue, frontend/src/pages/Lesson.vue
**Before:**
**After:**
- Also removed grouping in the main menu for login and logout
=> fix: improved lesson locked state

frontend/src/pages/JobDetail.vue, frontend/src/pages/JobForm.vue, lms/lms/api.py, lms/lms/doctype/lms_enrollment/lms_enrollment.json
1. Added country in job details.
2. Added country field in job form.
=> fix: country details in job page and form

frontend/index.html, frontend/src/components/AppSidebar.vue, frontend/src/components/Assessments.vue, frontend/src/components/BatchCourses.vue, frontend/src/components/BatchFeedback.vue, frontend/src/components/BatchOverlay.vue, frontend/src/components/BatchStudents.vue, frontend/src/components/CourseCardOverlay.vue, frontend/src/components/DesktopLayout.vue, frontend/src/components/DiscussionReplies.vue, frontend/src/components/Discussions.vue, frontend/src/components/LiveClass.vue, frontend/src/main.js, frontend/src/pages/Assignments.vue, frontend/src/pages/Batch.vue, frontend/src/pages/Batches.vue, frontend/src/pages/Courses.vue, frontend/src/pages/JobDetail.vue, frontend/src/pages/Jobs.vue, frontend/src/pages/Lesson.vue, frontend/src/pages/Profile.vue, frontend/src/pages/ProfileEvaluator.vue, frontend/src/pages/ProfileRoles.vue, frontend/src/pages/Programs.vue, frontend/src/pages/QuizForm.vue, frontend/src/pages/Quizzes.vue, frontend/src/utils/index.js, lms/www/lms.py
1. Learning time now won't have downtime during migration. https://docs.frappe.io/framework/user/en/zero*_downtime_migrations
2. The content would still be visible to all users. But they won't be able to add or edit any content.
=> feat: read only mode

cypress/e2e/course_creation.cy.js, cypress/support/commands.js, frontend/components.d.ts, frontend/package.json, frontend/src/components/AppSidebar.vue, frontend/src/components/BatchFeedback.vue, frontend/src/components/Categories.vue, frontend/src/components/CourseCardOverlay.vue, frontend/src/components/CourseReviews.vue, frontend/src/components/Evaluators.vue, frontend/src/components/Modals/FeedbackModal.vue, frontend/src/components/Modals/ReviewModal.vue, frontend/src/components/Modals/Settings.vue, frontend/src/pages/Batch.vue, frontend/src/pages/Batches.vue, frontend/src/pages/CourseDetail.vue, frontend/src/pages/Courses.vue, frontend/src/utils/index.js, lms/lms/doctype/lms_batch/lms_batch.json, lms/lms/doctype/lms_batch/lms_batch.py, lms/lms/doctype/lms_batch_feedback/lms_batch_feedback.json, package.json, yarn.lock
1. Moved batch feedback to the sidebar
2. Improved rating style on the Course Details page.
3. Fixed issue with onboarding banner not being visible when redirected from Persona Form.
4. Refactored Category list.
https://github.com/user-attachments/assets/8058a666-ab5b-44f4-abd8-3d227998d754
=> refactor: misc enhancements

frontend/src/App.vue, frontend/src/components/Modals/EvaluationModal.vue
- fix: some code semantics
- fix: `toast` used but not imported:
=> misc fixes

frontend/src/components/Settings/Settings.vue, frontend/src/pages/BatchForm.vue, frontend/src/pages/CourseForm.vue, frontend/src/utils/index.js, lms/lms/api.py
Admins can now add Meta Keywords and Description for courses and batches from their respective forms.
=> feat: seo tags and keywords for courses and batches

frontend/src/components/Settings/Settings.vue, lms/lms/api.py, lms/lms/doctype/lms_settings/lms_settings.json
=> feat: sidebar settings to toggle "Programming Exercise" menu

frontend/components.d.ts, frontend/src/components/CourseCardOverlay.vue, frontend/src/components/Modals/CourseProgressSummary.vue, frontend/src/pages/AssignmentSubmissionList.vue, frontend/src/pages/CourseDetail.vue, frontend/yarn.lock, lms/lms/api.py, lms/lms/doctype/lms_enrollment/lms_enrollment.json
The Course Progress Summary report was on the desk. Now that we are moving everything to the frontend, moving this report here too made sense. Moderators and Instructors can now see the progress summary from the Course Details page.
=> feat: course progress summary report

frontend/src/pages/Billing.vue
=> fix: state_translatability

frontend/components.d.ts, frontend/src/components/Quiz.vue, frontend/src/pages/CourseDetail.vue, lms/lms/doctype/lms_assignment_submission/lms_assignment_submission.json, lms/lms/utils.py
1. When completing a quiz, the lesson was not being marked as complete. The URL was being checked to get the lesson details. But because the quiz is rendered as an iframe, window.location.pathname was returning the path of the iframe. To fix this, the logic now gets the pathname as window.parent.location.pathname.
2. Fixed the page length issue for course and batch list.
=> fix: quiz progress issue

frontend/src/components/AppSidebar.vue, frontend/src/components/CourseCard.vue, frontend/src/components/Modals/CourseProgressSummary.vue, frontend/src/components/Modals/VideoStatistics.vue, frontend/src/pages/CertifiedParticipants.vue, frontend/src/utils/index.js, pyproject.toml
1. Removed the hover border on course cards
2. Added border to the course tags on the course card
3. Changed watch time on video statistics from seconds to minutes
=> fix: show video statistics watch time in minutes
